### ISSUE TITLE
Improve creation of new elements

### ISSUE THREAD

**Issue by prevwong** [prevwong/craft.js#10]
Currently when an element with `connector.create` is dragged to the `<Frame />`, it creates and appends a new Node (and thus renders a new instance of the User Element) to the first Canvas that cursor reaches. 

![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/16416929/72254366-cb9a9800-363e-11ea-8227-3f50e7eda921.gif)

I think that this "breaks" the user experience a little bit as it feels rather unnatural/unintuitive. 

I would prefer a solution similar to how Grape.js handles it:
![ezgif com-optimize (10)](https://user-images.githubusercontent.com/16416929/72258463-1d482000-3649-11ea-8252-5e6db9acb70f.gif)

Notice how the new element does not get rendered until dragging ends. This should be a rather simple fix at the [EventManager](https://github.com/prevwong/craft.js/blob/master/packages/core/src/events/EventManager.tsx)

**Comment by prateekrastogi** [comment]
Stop copying grape.js and instead look at sketch or adobexd for inspirations

**Comment by prevwong** [comment]
Your comment is unproductive and offer no real solutions. You're telling me to stop "copying" Grape.js but your alternative for me is to look to copy Sketch/XD instead ? Sketch/XD as far as I remember does not have the the same element positioning logic suitable for page editors unless you want your output to be completely absolute positioned.

**Comment by prateekrastogi** [comment]
good, keep working in your direction of thought. It will surely yield a sustainable solution

**Comment by ackvf** [comment]
When the component is placed immediately and `canDrag` logic is implemented, it might happen that the component refuses to drag. I believe that the component should be rendered only on mouseup event.
![drag-canDrag](https://user-images.githubusercontent.com/2313018/72552672-aeacd180-3897-11ea-9b4d-36270f3164bd.gif)
