### ISSUE TITLE
When setting a prop to null a warning is firing: `Cannot read property 'type' of null`

### ISSUE THREAD

**Issue by Tzelon** [prevwong/craft.js#103]
**Describe the bug**
When setting a prop to null a warning is firing:
`Cannot read property 'type' of null`

**To Reproduce**
1. Click the yellow box and watch the console.
2. Drag the yellow box and you will see this warning fires multiple times.
https://codesandbox.io/s/craftjs-cannot-read-property-type-of-null-czjmm?file=/src/App.tsx

**Expected behavior**
No warning. props can be null. 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | 0.1.0-beta.8
| React            | 16.12.0

**Comment by prevwong** [comment]
Hey @Tzelon 👋  Thanks for the sandbox demo, it was really helpful! The issue seems to have been the serialising function, the fix is now in 0.1.0-beta.9!
