### ISSUE TITLE
Cannot update a component (`re`) while rendering a different component (`k`)

### ISSUE THREAD

**Issue by codyng** [prevwong/craft.js#109]
Using the latest version (beta 10), when adding <Layers />, it shows this error:

Cannot update a component (`re`) while rendering a different component (`k`). To locate the bad setState() call inside `k`, follow the stack trace as described in https://fb.me/setstate-in-render

When not adding <Layers />, it is fine. Is it the internal error of craft.js/layers??

Testing Env:
React 16.13.1
create-react-app

  "dependencies": {
    "@craftjs/core": "0.1.0-beta.10",
    "@craftjs/layers": "0.1.0-beta.10",
    "@material-ui/core": "^4.11.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "material-ui-color-picker": "^3.5.0",
    "react": "^16.13.1",
    "react-contenteditable": "^3.3.5",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  }

Following the basic tutorial: https://craft.js.org/r/docs/guides/basic-tutorial and add <Layers /> at the end.

<img width="577" alt="Screenshot 2020-07-24 at 13 37 55" src="https://user-images.githubusercontent.com/4618641/88363521-f0708480-cdb2-11ea-850c-9665a6eec7eb.png">

**Comment by RaGreen** [comment]
Bumb, builded @craftjs/layers with sourcemaps:
![image](https://user-images.githubusercontent.com/1823017/90454788-7f439900-e0f4-11ea-9df1-4035face6972.png)

**Comment by RaGreen** [comment]
Problem is generated by actions.registerLayer(id) in LayerNode.tsx:46 to 51

```
const initRef = useRef<boolean>(false);

if (!initRef.current) {
    actions.registerLayer(id);
    initRef.current = true;
}
```

**Comment by RaGreen** [comment]
IMHO best option to resolve it is using useEffect hook to register layer.

```
useEffect(() => {
    if (!initRef.current) {
      actions.registerLayer(id);
      initRef.current = true;
    }
}, [ initRef ]);
```

**Comment by codyng** [comment]
Is it possible to by-pass this error by modifying the source code??
The error is generated when I call <Layers expandRootOnLoad={true} />

**Comment by codyng** [comment]
Good answer! Thanks RaGreen!
It's better to fix this problem in next version.

**Comment by dbousamra** [comment]
Is this fixed?

**Comment by everblaze** [comment]
I have this same error and don't see a solution anywhere?

**Comment by prevwong** [comment]
Fixed in #246 and released in 0.1.0-beta.18 (or 0.2.0-alpha-24)

**Comment by everblaze** [comment]
thanks, when I upgrade I have to beta.18 seems like layers are dependant on @craftjs/core@"^0.2.0-alpha.19". I can see any upgrade notes to alpha and it crashes my working editor. Is there a breaking changes list?

**Comment by everblaze** [comment]
seems like it's not possible to install layers now unless you have the alpha core package?

**Comment by prevwong** [comment]
@everblaze Sorry my bad, please try again with beta.19 😅  (I will fix the release flow in the coming week)

**Comment by everblaze** [comment]
Thanks, working a treat now!
