### ISSUE TITLE
Improve connectors

### ISSUE THREAD

**Issue by ackvf** [prevwong/craft.js#12]
Currently the usage is this

```
const { connectors: { connect, drag } } = useNode();

// and then
   return <div ref={connect}>

// which is basically this
   return <div ref={ref => connect(ref)}>

// or with drag
   return <div ref={ref => connect(drag(ref))}>
```

Could we instead use this pattern, so that in future, when there are more methods, we can combine them simpler?

```
   return <div ref={ref => connect(ref, drag, drop)}>
  
// instead of
   return <div ref={ref => connect(drag(drop(ref)))}/>
```
or even let connect() return curried itself if it doesn't detect a ref for these cases

```
   return <div ref={connect}> // this is OK already
   return <div ref={ref => connect(ref)}> // this is OK already

   return <div ref={connect()}>
   return <div ref={ref => connect()(ref)}>
   return <div ref={connect(drag)}>
   return <div ref={connect(drag, drop)}>
   return <div ref={ref => connect(drag, drop)(ref)}>
```

**Comment by prevwong** [comment]
This is interesting but is there a real need for this ? Personally, I don't think it makes much of a difference in terms of simplicity  😄
```jsx
return <div ref={ref => connect(ref, drag, drop)}>
```
Also, I think this will add a bit more complexity since now the wrapper for the connectors will have to loop the rest parameters and pass the `ref` to each of the additional connectors passed.

**Comment by prevwong** [comment]
I will reply your question regarding why we don't have a `drop` connector from the earlier issue here as it seems more fitting.

There is no `drop` connector because of the core concepts in Craft.js (Nodes and Canvas Nodes). The `<Canvas />` component, creates a `Canvas` Node (droppable region) and enables each of its immediate child Node to be draggable. The `<Canvas />` component then renders each Node by its element `type`. 

If we expose a `drop` connector, then it must somehow also control what the connected DOM would render, which is not ideal since we want React to handle rendering.

p.s. Consider joining our [Discord](https://discord.gg/Rx5uJuU) server 👋🏽

**Comment by ackvf** [comment]
My reasoning behind this was based on the wrong understanding of what is what. I thought that connect is somehow responsible for the magic enhancements, but instead, they (connect, drag) are equal. It could as well be written (and I have just tested that it works) as

```
ref => { drag(ref); connect(ref); }
ref => { drag(connect(ref)) }
ref => { connect(drag((ref)) }
```

It's not that one initializes the other, they just return back the reference for comfort so that we don't have to call them separately. Anyway it would still be cool if we could avoid typing `ref => xxx(ref)` as in the examples here https://craft.js.org/r/docs/concepts/user-components where it uses this pattern (as the one I suggested):

```
const Hero = ({title, children}) => {
  const { connectors: {connect, drag} } = useNode();
  return (
    <div ref={connect(drag)}>
      <h2>{title}</h2>
      <div>
        {children}
      </div>
    </div>
  )
}
```

**Comment by ackvf** [comment]
I will fix the examples in docs together with other improvements (as discussed on Discord), as well as addressing #11 and the other Canvas use example.

**Comment by prevwong** [comment]
@ackvf  As of now, I'm still not convinced of the proposed API yet. Firstly, as I've mentioned, we would be required to deal with rest parameters and perform some looping, thus increasing complexity.

Secondly, I assume this would also lead us to introduce more variations on how the connectors should be used.

Let's consider the several different ways to utilise the connectors:
```jsx
// 1) simple ref
ref={connect(drag)}

// 2) callback ref
ref={dom => {
  connect(drag)(dom); // ok
  
  // 3) what if we only want to use one connector 
  //  this pattern looks very awkward
  connect()(dom);
  drag()(dom);
}}
```

`#3` looks awkward, instead I'm sure we would want this:
```jsx
ref={dom => {
   // if connectors passed, then return a function that would pass the DOM
   connect(drag)(dom);

   // if no connectors passed, then directly pass the DOM
   drag(dom); 
}}
```

Essentially, I feel that this would actually cause more confusion than actually be convenient. Also, I've no idea how would be able to document this clearly, especially the typings 😆

**Comment by ackvf** [comment]
The thing is that all the suggested patterns would be supported.

```
ref={connect} // or ref={drag}
ref={ref => connect(ref)

ref={connect(drag)}
ref={ref => connect(drag)(ref)}
```


```
ref={dom => {  
  // this won't be necessary 
  connect()(dom);
  drag()(dom);

  // as this will work
  connect(dom);
  drag(dom);
}}
```

all connectors would be abstracted away behind a common "invoker", which would be allowed to accept other connectors or ref.
[Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=41&pc=1#code/JYOwLgpgTgZghgYwgAgMIHsQggs6rIDeAUMmcgBRQQwBcyAEgCoCyAMgKIA2EAthOACU9Zu258BYUuQoA6eQkzZc+AM70MWHHigBtALrC0S7fmIB6c+UrU6jVpx79wAGmTzZirSqjrj3nQMjUUcJcGIAX2ILKzAAC2BVZETkeJRQSCgQOC5k3gAHJ0k4MGBMYgATHC44amQvVTBkkAA3dABrCAARKDgAc3oqGhEHcWcwQWQAXgA+ZDbgCoBuSuralAam0DbOzWUwQdsRsSKhabmF5ejN5p3oWj3TAinKD1q+vzgQAE8g+i-vuciNIyDwmrZpsh3qpdAAGfQg5IwGw0ZqNL5IdDIkJjSSTEjWaw3Lz7NSQ6GyVRcYBICgARkEiOswGRFBJT1Ush4ID68XxTMJZEs9RyuVF9RMPiSAHdgPFUnEUBDQOiQEgBYL2VLZDB8BxEHE2UCEBRoYJGYKyBFLcgNchqGAAK5Ze00RHWiBcVTpVnKkCqzHIgBijrVpUw+OQwulGy+yAgLQEyFU+RwLMB72mUxeFV6fWQAB8C1CoPnsy8tVIbQ7nSBKNCAEz-H6TWa3DrQOTyRtuN6l1QW8hRKLRYWYLiA+IpFIQAAe+XwkAqqXQyEd3qg0TnC6gTWJkqaL22HagFGPuwPUKSjx8jO3i4l-qauf6kPPnffPVfcGvB-wjNHKw5zgAoeFUaIqgQGo6jBV07BxU4pGIG4oDpSFKyGGBJmFBCwikFCG3Qg8KBfPpsKsG8dGuTBGntABmSFSLZYjbHNKMrFw8ZkJo8EABZGLzZiAkETDyPsE48OIIA)
```
interface Connector {
    (ref: HTMLElement): HTMLElement
    (...connectors: Connector[]): Connector
//    (ref: HTMLElement, ...connectors: Connector[]): HTMLElement
}

// this is the internal implementation
declare const invokeDrag: (ref: HTMLElement) => void;
declare const invokeConnect: (ref: HTMLElement) => void;

const invoker:Connector = (...args: any[]): any => {
    let ref = args[0]
    if (ref instanceof HTMLElement) {
        const connectors = args.slice(1)
        if (connectors.length) {
            // call all connectors with the ref instance
            connectors.forEach(c => c(args))
        }        
        return ref
    } else if (ref instanceof Function) { // we can even specify arg === drag || arg === connect
        return (args2: any) => invoker(...args2, ...args)
    }
}


// only this is exported to user

export const connect = invoker(invokeConnect as Connector)
export const drag = invoker(invokeDrag as Connector)


// examples

declare let ref: HTMLElement

const r1 = connect(ref) // HTMLElement
const r2 = connect(drag) // Connector

const r3 = drag(connect(ref)) // HTMLElement
const r4 = drag(connect)(ref) // HTMLElement
```

**Comment by prevwong** [comment]
I know it's possible, but like I said: increased complexity with the rest parameters and looping.

```jsx
ref={dom => {  
  // this won't be necessary 
  connect()(dom);
  drag()(dom);

  // as this will work
  connect(dom);
  drag(dom);
}}
```

When I was talking about the variations, this is what I meant too. There are now more ways to do the same thing, which might be difficult to document and more difficult for maintenance. 

To further illustrate the variations, with the proposed implementation, we must take care how the connectors in `useEditor` works as well. Those connectors have at least 2 parameters (the first being a DOM element, and the second is unique to each connector)

```jsx
const { connectors: {select, create} } = useEditor();
select(HTMLElement, NodeId)
create(HTMLElement, Node)

// current implementation
ref={dom => 
  select(create(dom, newNode), 'node-a')
}

// new implementation
ref={dom => {
  select(create)(dom, /* what goes in here ? */) 

  // or do it manually, in which case it is the same as the current API ? 
  select(dom, 'node-a');
  create(dom, newNode);
}} // how to specify the second parameter ? 
```

What I'm trying to show here is, with the current implementation, although it might look a bit messy, there is really just one way of using it and arguable less confusing. 

While with the new implementation, we can either use the current API style or chain the connectors in the first parameter as a shortcut, which is fine until you need to specify additional parameters to each connector. For me, I'm not sure if it's worth the added complexity and maintenance.

If you still strongly believe in this, feel free to submit a PR so we can have a look at it from there. Although I'm still skeptical, I could be wrong 😄😂
