### ISSUE TITLE
Save the final value in the history when throttling a property change with setProp

### ISSUE THREAD

**Issue by antoineol** [prevwong/craft.js#155]
Thanks for this great lib! I've enjoyed the tutorial. It's promising!

**Is your feature request related to a problem? Please describe.**

Currently, the throttle we can apply with setProp (from useNode) skips the latest changes in the value. It is quite misleading for the user, since he expects the last value entered to be saved in the history, which is not the case now for fast changes.

Example:

- Take any of the demos available ([here](https://craft.js.org/examples/basic/) and [there](https://craft.js.org/))
- Change a Text font size to a big value with the slider
- Undo the change, then redo it until you can't redo. Notice that the last value in the history is _not_ the big font size, but an intermediate value.

**Describe the solution you'd like**

At least, the last value should be saved in the history, as the debounce would. And in my opinion, a debounce is better than a throttle here. I assume that when fast changes happen in a property, intermediate values don't matter. However, throttle vs debounce is less important. The final value is the big thing which is missing in the history.

Oh and by the way, why not a global default throttling/debouncing config to avoid replicating it in all `setProp`'s? :)

**Comment by prevwong** [comment]
Hi @antoineol! 

> Oh and by the way, why not a global default throttling/debouncing config to avoid replicating it in all setProp's? 
Yeah, this is probably a good idea! 😄 

As for the history bug, this should be fixed now in 0.1.0-beta.14 (sorry for publishing the package late, the fix was already merged a couple of weeks prior).  Closing for now, but feel free to reopen if the issue persists!

**Comment by antoineol** [comment]
It seems all good, thanks!
