### ISSUE TITLE
Regression in beta.14: Problem with lodash

### ISSUE THREAD

**Issue by ankri** [prevwong/craft.js#165]
**Describe the bug**
When starting a brand new project with beta.14 with only CRA as dependency you get:
![image](https://user-images.githubusercontent.com/2842920/105630473-bf4c3c00-5e49-11eb-88e5-c34d23186f2f.png)

When starting a brand new project with beta.14 and ViteJS, you get
![image](https://user-images.githubusercontent.com/2842920/105630489-d2f7a280-5e49-11eb-9cfd-e097cbc152b1.png)

**To Reproduce**
Create a new Codesandbox and add craft as dependency. Import `<Editor />` and it crashes.

A sample Codesandbox: https://codesandbox.io/s/ecstatic-fermat-39byx?file=/src/App.tsx

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | beta.14
| React            | 17 (Just to be sure I also tested it with react-scripts 3.x and React 16)
| Other dependencies | Create React App / ViteJS

---

It works with beta.13 or by manually adding lodash as a dependency.

---

When looking through the commits since beta.13, I sadly could not find the commit that broke it otherwise I would have opened a PR. Do you have any idea?

I only found this [Commit](https://github.com/prevwong/craft.js/commit/98bfee4dea28ccc022e8721932262bc0f7c7a727) that referenced lodash.

**Comment by prevwong** [comment]
Sorry about that, we recently exported some of the test utilities in https://github.com/prevwong/craft.js/commit/c47cacd9b40ebecd88133ff0f72407be0104a353 which uses a lodash function and I did not realize that the package.json did not explicitly include it 😅 

Should be fixed now in beta.15!
