### ISSUE TITLE
demo not working throw error on drag

### ISSUE THREAD

**Issue by mrsavari** [prevwong/craft.js#167]
**Describe the bug**
crashes when start drag an element from any where to any where !

**Additional context**
Uncaught ReferenceError: events is not defined
    at te (index.js:15)
    at renderWithHooks (react-dom.development.js:16241)
    at updateFunctionComponent (react-dom.development.js:18328)
    at beginWork$1 (react-dom.development.js:20151)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at beginWork$$1 (react-dom.development.js:25738)
    at performUnitOfWork (react-dom.development.js:24662)
    at workLoopSync (react-dom.development.js:24638)
    at performSyncWorkOnRoot (react-dom.development.js:24237)
    at react-dom.development.js:12180
    at unstable_runWithPriority (scheduler.development.js:818)
    at runWithPriority$2 (react-dom.development.js:12130)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12175)
    at flushSyncCallbackQueue (react-dom.development.js:12163)
    at scheduleUpdateOnFiber (react-dom.development.js:23676)
    at dispatchAction (react-dom.development.js:17057)
    at Object.Y.t.reduce.t.<computed> [as setIndicator] (index.js:1)
    at t.dropElement (index.js:15)
    at index.js:15
    at HTMLButtonElement.a (index.js:15)
te @ index.js:15
renderWithHooks @ react-dom.development.js:16241
updateFunctionComponent @ react-dom.development.js:18328
beginWork$1 @ react-dom.development.js:20151
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
beginWork$$1 @ react-dom.development.js:25738
performUnitOfWork @ react-dom.development.js:24662
workLoopSync @ react-dom.development.js:24638
performSyncWorkOnRoot @ react-dom.development.js:24237
(anonymous) @ react-dom.development.js:12180
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12130
flushSyncCallbackQueueImpl @ react-dom.development.js:12175
flushSyncCallbackQueue @ react-dom.development.js:12163
scheduleUpdateOnFiber @ react-dom.development.js:23676
dispatchAction @ react-dom.development.js:17057
Y.t.reduce.t.<computed> @ index.js:1
t.dropElement @ index.js:15
(anonymous) @ index.js:15
a @ index.js:15
index.js:1 The above error occurred in the <te> component:
    in te (created by Se)
    in Se (at pages/index.js:28)
    in div (at pages/index.js:24)
    in App (at _app.js:29)
    in ThemeProvider (at _app.js:26)
    in MyApp
    in Container (created by AppContainer)
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, MyApp.
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2430
logCapturedError @ react-dom.development.js:21810
logError @ react-dom.development.js:21847
callback @ react-dom.development.js:23235
callCallback @ react-dom.development.js:13810
commitUpdateEffects @ react-dom.development.js:13848
commitUpdateQueue @ react-dom.development.js:13838
commitLifeCycles @ react-dom.development.js:22102
commitLayoutEffects @ react-dom.development.js:25302
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
commitRootImpl @ react-dom.development.js:25040
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12130
commitRoot @ react-dom.development.js:24889
finishSyncRender @ react-dom.development.js:24296
performSyncWorkOnRoot @ react-dom.development.js:24274
(anonymous) @ react-dom.development.js:12180
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12130
flushSyncCallbackQueueImpl @ react-dom.development.js:12175
flushSyncCallbackQueue @ react-dom.development.js:12163
scheduleUpdateOnFiber @ react-dom.development.js:23676
dispatchAction @ react-dom.development.js:17057
Y.t.reduce.t.<computed> @ index.js:1
t.dropElement @ index.js:15
(anonymous) @ index.js:15
a @ index.js:15
_app.js:7 Uncaught ReferenceError: events is not defined
    at te (index.js:15)
    at renderWithHooks (react-dom.development.js:16241)
    at updateFunctionComponent (react-dom.development.js:18328)
    at beginWork$1 (react-dom.development.js:20151)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at beginWork$$1 (react-dom.development.js:25738)
    at performUnitOfWork (react-dom.development.js:24662)
    at workLoopSync (react-dom.development.js:24638)
    at performSyncWorkOnRoot (react-dom.development.js:24237)
    at react-dom.development.js:12180
    at unstable_runWithPriority (scheduler.development.js:818)
    at runWithPriority$2 (react-dom.development.js:12130)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12175)
    at flushSyncCallbackQueue (react-dom.development.js:12163)
    at scheduleUpdateOnFiber (react-dom.development.js:23676)
    at dispatchAction (react-dom.development.js:17057)
    at Object.Y.t.reduce.t.<computed> [as setIndicator] (index.js:1)
    at t.dropElement (index.js:15)
    at index.js:15
    at HTMLButtonElement.a (index.js:15)
te @ index.js:15
renderWithHooks @ react-dom.development.js:16241
updateFunctionComponent @ react-dom.development.js:18328
beginWork$1 @ react-dom.development.js:20151
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
beginWork$$1 @ react-dom.development.js:25738
performUnitOfWork @ react-dom.development.js:24662
workLoopSync @ react-dom.development.js:24638
performSyncWorkOnRoot @ react-dom.development.js:24237
(anonymous) @ react-dom.development.js:12180
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12130
flushSyncCallbackQueueImpl @ react-dom.development.js:12175
flushSyncCallbackQueue @ react-dom.development.js:12163
scheduleUpdateOnFiber @ react-dom.development.js:23676
dispatchAction @ react-dom.development.js:17057
Y.t.reduce.t.<computed> @ index.js:1
t.dropElement @ index.js:15
(anonymous) @ index.js:15
a @ index.js:15
index.js:1 The above error occurred in the <MyApp> component:
    in MyApp
    in Container (created by AppContainer)
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, Container.
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2430
logCapturedError @ react-dom.development.js:21810
logError @ react-dom.development.js:21847
callback @ react-dom.development.js:23235
callCallback @ react-dom.development.js:13810
commitUpdateEffects @ react-dom.development.js:13848
commitUpdateQueue @ react-dom.development.js:13836
commitLifeCycles @ react-dom.development.js:22102
commitLayoutEffects @ react-dom.development.js:25302
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
commitRootImpl @ react-dom.development.js:25040
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12130
commitRoot @ react-dom.development.js:24889
finishSyncRender @ react-dom.development.js:24296
performSyncWorkOnRoot @ react-dom.development.js:24274
(anonymous) @ react-dom.development.js:12180
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12130
flushSyncCallbackQueueImpl @ react-dom.development.js:12175
flushSyncCallbackQueue @ react-dom.development.js:12163
scheduleUpdateOnFiber @ react-dom.development.js:23676
dispatchAction @ react-dom.development.js:17057
Y.t.reduce.t.<computed> @ index.js:1
t.dropElement @ index.js:15
(anonymous) @ index.js:15
a @ index.js:15
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Se (at pages/index.js:28)
    in div (at pages/index.js:24)
    in App (at _app.js:29)
    in ThemeProvider (at _app.js:26)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2430
warningWithoutStack @ react-dom.development.js:530
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.development.js:25696
scheduleUpdateOnFiber @ react-dom.development.js:23646
dispatchAction @ react-dom.development.js:17057
Y.t.reduce.t.<computed> @ index.js:1
t.dropElement @ index.js:15
(anonymous) @ index.js:15
a @ index.js:15

**Comment by prevwong** [comment]
Fixed in 0.1.0-beta.16!
