### ISSUE TITLE
actions.serialize() should return only the nodes that are necessary

### ISSUE THREAD

**Issue by timc1** [prevwong/craft.js#179]
**Describe the bug**

The `EditorState` grows as more blocks are added to the canvas; however, when a block is deleted the linkedNodes still exist in the tree

**To Reproduce**

1. Add a few blocks and serialize the state of the editor
2. Delete all blocks – then serialize again
3. Notice the `ROOT` contains no `linkedNodes` and `nodes`, but the references to the old nodes still exist

<img width="402" alt="Screen Shot 2021-02-09 at 1 24 39 PM" src="https://user-images.githubusercontent.com/12195101/107409441-2caecc80-6ada-11eb-8d53-7d060352b9a9.png">

**Comment by nicosh** [comment]
I have the same issue, and this is really annoying when you save data to db since you use a lot of unnecessary space. Also react hydration data is bigger  that needed.

**Comment by timc1** [comment]
@nicosh I was able to get a sanitized version of what `serialize` returned like so  👍

```js
import { SerializedNode } from "@craftjs/core";

function getDescendants(
  parsedData: Record<string, SerializedNode>,
  nodeId: string
) {
  const nodes = {};

  function recursiveMap(nodeId) {
    const node = parsedData[nodeId];

    // Add Child nodes
    node.nodes.forEach((nodeId) => recursiveMap(nodeId));

    // Add linked nodes
    Object.keys(node.linkedNodes).map((key) => {
      const nodeId = node.linkedNodes[key];
      return recursiveMap(nodeId);
    });

    nodes[nodeId] = node;
  }
  recursiveMap(nodeId);
  return nodes;
}

/**
 * `sanitizeSerializedData`
 * Starting from a `rootId`, return only the necessary 
 * nodes by traversing child and linked nodes.
 */
export default function sanitizeSerializedData(
  serializedData: string,
  rootId: string
): Record<string, SerializedNode> {
  try {
    const parsed = JSON.parse(serializedData);
    const nodes = getDescendants(parsed, rootId);
    return nodes;
  } catch (error) {
    return {};
  }
}

```

**Comment by prevwong** [comment]
Closing as this has been fixed! 💯
