### ISSUE TITLE
useEditor actions.setProp documentation is incorrect 

### ISSUE THREAD

**Issue by hdaggett** [prevwong/craft.js#19]
When I try to use `actions.setProp` from `useEditor`, it expects the second argument to be a function, not an object. I tried passing a function that returned an object with the props I wanted to change, but that doesn't appear to work either.

What is the proper usage for `actions.setProp`?

**Comment by prevwong** [comment]
@hdaggett Will fix the docs tomorrow. The type signature is actually: 
`setProp: (id: NodeId, cb: (props: any) => void)`

eg:
```jsx
actions.setProp(id, (props) => {
   props.text = "new value";
});
```
