### ISSUE TITLE
How can I change component props before query.createNode or actions.add?

### ISSUE THREAD

**Issue by linxianxi** [prevwong/craft.js#199]
like this. I want to set defaultProps to the Cell component.How can i set width to it? @prevwong 

```
let width;
// ...calculate the width
const node = query.createNode(<Element canvas is={Cell} />);
actions.add(node, id);
```

**Comment by prevwong** [comment]
Hi! Can you try and see if the following works for you:

```tsx
const node = query.parseFreshNode({
   data: {
       type: Cell,
       isCanvas: true,
       props: {
          width
      }
    }
}).toNode();

actions.add(node, id);

**Comment by linxianxi** [comment]
> 你好！您能否尝试一下，看看是否适合您：
> 
> ```tsx
> const  node  = 查询。parseFreshNode （{
>    数据：{
>        类型：单元格，
>        isCanvas：true ，
>        道具：{
>           宽度
>       } 
>     } 
> } ）。toNode （）;
> 
> 行动。添加（节点， id ）;
> ```



> Hi! Can you try and see if the following works for you:
> 
> ```tsx
> const node = query.parseFreshNode({
>    data: {
>        type: Cell,
>        isCanvas: true,
>        props: {
>           width
>       }
>     }
> }).toNode();
> 
> actions.add(node, id);
> ```

Thanks!
