### ISSUE TITLE
How do I merge two histories into one？

### ISSUE THREAD

**Issue by linxianxi** [prevwong/craft.js#204]
### Where need to be used.
I have a  column component.It can resize.

![image](https://user-images.githubusercontent.com/47104575/109252578-e0c58c80-7828-11eb-8a0b-6475700ebb1d.png)

### example 1
like this.I set two Ids at the same time.And then I use history.undo. You know...  @prevwong 
```
actions.setProp(id, (props) => {
  props.width = value1;
});

actions.setProp(nextId, (props) => {
  props.width = value2;
});
```

### example 2
 I want to set the history when onResizeStop ,but value2 = value1, history has not changed.Any idea?
```
onResize = {( ) => {
  const value1 = ...;
  actions.history.ignore().setProp(id, (props) => {
    props.width = value1
  })
}}

onResizeStop = {( ) => {
  // value2 = value1
  const value2 = ...;
  actions.setProp(id, (props) => {
    props.width = value2;
  })
}}

```

**Comment by prevwong** [comment]
Hm, why do you need to `setProp` in `onResizeStop`?

Couldn't you just `setProp` in `onResize`?

**Comment by linxianxi** [comment]
> Hm, why do you need to `setProp` in `onResizeStop`?
> 
> Couldn't you just `setProp` in `onResize`?

Because I only want to make history once. If I use throttling in onResize, it will generate multiple histories

**Comment by linxianxi** [comment]
@prevwong any idea for example1 and example2？

**Comment by ankri** [comment]
I have this one in my project, maybe you can utilize it:

```ts
import * as React from 'react';
import { useEditor, useNode } from '@craftjs/core';

/**
 * Enables live updating a prop. This hooks does not pollute the undo/redo history and only adds to the history when calling `addToHistory`.
 * To update the prop value call `updatePropValue`.
 *
 * @param propName The name of the prop e.g. `label`
 */
export const useLivePropUpdate = function <T>(
  propName: string,
): {
  /**
   * submit the value to the history
   */
  addToHistory: () => void;
  /**
   * Update the prop's value
   */
  updatePropValue: (value: T) => void;
} {
  // We want to support live updating of a prop
  // But we do not want to pollute the history. Therefor we need to use actions.history.ignore().setProp() to bypass the history
  // Sadly that leads to a problem when calling setProp without ignoring the history (in onSubmit) to not write a history entry. Because craft's state manager
  // the prop does not change
  // So we add the history entry manually

  const { props, id } = useNode((node) => ({
    props: node.data.props,
  }));
  const { actions, store } = useEditor();
  // to add the history entry manually we need to save the oldValue before editing starts
  const oldValue = React.useRef<T>(props[propName]);
  // We also need to have a reference to the new value, for the unmount case (see below)
  const newValue = React.useRef<T>(props[propName]);
  const { setProp: ignoredSetProp } = actions.history.ignore();

  // we manually add the prop change to the history
  const saveToHistory = React.useCallback(() => {
    const timelinePath = ['nodes', id, 'data', 'props', propName];
    if (oldValue.current !== newValue.current) {
      store.history.add(
        [{ op: 'replace', path: timelinePath, value: newValue.current }],
        [
          {
            op: 'replace',
            path: timelinePath,
            value: oldValue.current,
          },
        ]
      );
    }
  }, []);

  // We have an onBlur listener on the text field  that updates the props value. The onBlur listener fires an onSubmit, which
  // should call `addToHistory`
  // Sadly the onBlur listener does not fire, when we use the field in a PopOver because closing the PopOver (unblur) leads to an unmount of the component which fires
  // before the onSubmit. So we need to update the history on unmount, too
  React.useEffect(() => {
    return () => {
      saveToHistory();
    };
  }, []);

  const addToHistory = () => {
    saveToHistory();

    // We need to update the oldValue so that we do not write another history entry when we unmount the component
    oldValue.current = newValue.current;
  };

  const updatePropValue = (newPropValue: T) => {
    ignoredSetProp(id, (props) => {
      props[propName] = newPropValue;
    });
    newValue.current = newPropValue;
  };

  return { addToHistory, updatePropValue };
};
```

We use `updatePropValue` to update the prop value (in my case a label from the sidebar) and submit it to history with `addToHistory`. This way you can update the props without polluting the history

**Comment by linxianxi** [comment]
@prevwong But if I set two ids at the same time,How do I undo these two at once(example 1). And can you tell me how to use store.history.add?Like it is params...

**Comment by linxianxi** [comment]
@ankri  #206 Hi,I used your method,do you have this problem after history.add？

**Comment by ankri** [comment]
> And can you tell me how to use store.history.add?Like its params...

It uses [Patches from immer](https://immerjs.github.io/immer/docs/patches)

**Comment by linxianxi** [comment]
> > And can you tell me how to use store.history.add?Like its params...
> 
> It uses [Patches from immer](https://immerjs.github.io/immer/docs/patches)

How do I write store.history.add if I delete one id at the same time and change the width of multiple ids? Please help me, thank you!!!

**Comment by ankri** [comment]
You add more items to the arrays:

```js
      store.history.add(
        [
             { op: 'replace', path: timelinePath, value: newValue.current },
             // here 
        ],
        [
          {
            op: 'replace',
            path: timelinePath,
            value: oldValue.current,
          },
          // and here
        ]
      );
```

**Comment by linxianxi** [comment]
> ```js
> timelinePath
> ```

This is modify properties, I already know that.What if you delete it? What should timelinePath be?

**Comment by linxianxi** [comment]
> You add more items to the arrays:
> 
> ```js
>       store.history.add(
>         [
>              { op: 'replace', path: timelinePath, value: newValue.current },
>              // here 
>         ],
>         [
>           {
>             op: 'replace',
>             path: timelinePath,
>             value: oldValue.current,
>           },
>           // and here
>         ]
>       );
> ```



> You add more items to the arrays:
> 
> ```js
>       store.history.add(
>         [
>              { op: 'replace', path: timelinePath, value: newValue.current },
>              // here 
>         ],
>         [
>           {
>             op: 'replace',
>             path: timelinePath,
>             value: oldValue.current,
>           },
>           // and here
>         ]
>       );
> ```

This is modify properties, I already know that.What if you delete it? What should timelinePath be?

**Comment by ankri** [comment]
Like I said, craft uses [patches from immer](https://immerjs.github.io/immer/patches/). Please have a look at the documentation. There are examples on different operations than `replace`. You can use `add` and `remove`.

```js
[
    {
        "op": "replace",
        "path": ["profile"],
        "value": {"name": "Veria", "age": 5}
    },
    {"op": "remove", "path": ["tags", 3]}
]```

```js
[
    {"op": "replace", "path": ["profile"], "value": {"name": "Noa", "age": 6}},
    {"op": "add", "path": ["tags", 3], "value": "kiddo"}
]
```

**Comment by linxianxi** [comment]
> Like I said, craft uses [patches from immer](https://immerjs.github.io/immer/patches/). Please have a look at the documentation. There are examples on different operations than `replace`. You can use `add` and `remove`.
> 
> ```js
> [
>     {
>         "op": "replace",
>         "path": ["profile"],
>         "value": {"name": "Veria", "age": 5}
>     },
>     {"op": "remove", "path": ["tags", 3]}
> ]
> ```
> 
>  ```js
> [
>     {"op": "replace", "path": ["profile"], "value": {"name": "Noa", "age": 6}},
>     {"op": "add", "path": ["tags", 3], "value": "kiddo"}
> ]
> ```

can you give me a remove example？If id is “abc”

**Comment by linxianxi** [comment]
> Like I said, craft uses [patches from immer](https://immerjs.github.io/immer/patches/). Please have a look at the documentation. There are examples on different operations than `replace`. You can use `add` and `remove`.
> 
> ```js
> [
>     {
>         "op": "replace",
>         "path": ["profile"],
>         "value": {"name": "Veria", "age": 5}
>     },
>     {"op": "remove", "path": ["tags", 3]}
> ]
> ```
> 
> ```js
> [
>     {"op": "replace", "path": ["profile"], "value": {"name": "Noa", "age": 6}},
>     {"op": "add", "path": ["tags", 3], "value": "kiddo"}
> ]
> ```

How do I convert `actions.delete(id)` to store.history.add?

**Comment by addlistener** [comment]
https://github.com/prevwong/craft.js/commit/8016b82bf26dd208a17df59c93ed7f46cbee955f

For anyone ended up here. `actions.history.merge()` works like a charm
