### ISSUE TITLE
npm audit immer

### ISSUE THREAD

**Issue by timc1** [prevwong/craft.js#205]
The library is currently using an old version of `immer`, which doesn't pass an npm audit. Any chance or plan of updating?

<img width="594" alt="Screen Shot 2021-02-26 at 9 17 45 AM" src="https://user-images.githubusercontent.com/12195101/109311198-7d7d2f80-7813-11eb-8f26-db17ee6911b0.png">

**Comment by prevwong** [comment]
Yeah, will be updating this!

**Comment by deepakkj** [comment]
Is this fixed?

**Comment by deepakkj** [comment]
PR #211 raised for this fix. Could you please review this? @prevwong Thank you

**Comment by prevwong** [comment]
Fixed in 0.2.0-alpha.17. 

Thanks again @deepakkj!

**Comment by timc1** [comment]
@prevwong we'll need to update core as well yea? https://github.com/prevwong/craft.js/blob/next/packages/core/package.json#L41

**Comment by prevwong** [comment]
@deepakkj @timc1 Unfortunately there was a regression in #211 which has been fixed in #214. Additionally, `immer` is no longer a dependency in core so that should make things a little bit simpler now.

**Comment by timc1** [comment]
💯 can we get alpha@18 out with that fix?

**Comment by prevwong** [comment]
Yeap, auto-publish is working again, so anytime now 😄

**Comment by deepakkj** [comment]
> @deepakkj @timc1 Unfortunately there was a regression in #211 which has been fixed in #214. Additionally, `immer` is no longer a dependency in core so that should make things a little bit simpler now.

Thank you. @prevwong What were the regression and how did we identify it?
