### ISSUE TITLE
Layers package is using react-contenteditable but not in the package.json

### ISSUE THREAD

**Issue by dbousamra** [prevwong/craft.js#213]
**Describe the bug**
I receive an error when using layers in my own project, complaining about react-contenteditable missing.
I noticed the code is using it, but it's not added as a dependency: https://github.com/prevwong/craft.js/blob/v0.1.0-beta.16/packages/layers/src/layers/DefaultLayer/EditableLayerName.tsx#L3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         |
| React            |
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by sudarshan777** [comment]
I am also facing the same problem.

**Comment by cephirothdy2j** [comment]
Same issue here. You can get around it by running `yarn add react-contenteditable`. But then you'll hit the same problem for `styled-components`, which you can get around with `yarn add styled-components`. After that, my project will build successfully.
