### ISSUE TITLE
Adding Call to Action

### ISSUE THREAD

**Issue by throne1986** [prevwong/craft.js#223]
Hi All

I am a newbie to this great library, is it possible when the user adds a button to add a call to action on this button eg open URL, or any other actions? if it's possible can someone provide a demo on code sandbox?

![image](https://user-images.githubusercontent.com/27904724/111798933-d4ce6700-88ca-11eb-9aad-93249cf4899a.png)

**Comment by ankri** [comment]
Related [discussion](https://github.com/prevwong/craft.js/discussions/220)

@throne1986  Do you mind closing this issue in favor of using the discussion? Let's keep "issues" for bug reports.

**Comment by throne1986** [comment]
okay let just put it into discussion, thanks bro
