### ISSUE TITLE
Stagnant linked nodes remain in json after parent is deleted.

### ISSUE THREAD

**Issue by Spenc84** [prevwong/craft.js#228]
**Describe the bug**
When deleting a node that has linked nodes assigned to it, the node itself is removed from the json but it's linked nodes are not. 

**To Reproduce**
Create a node that renders a linked node and then delete it and check the resulting json. The original node will be gone but the linked node will remain in the json even though it no longer has a parent to render it.

**Expected behavior**
When a node is deleted it's linked nodes should be removed along with it's child nodes.

**Comment by nicosh** [comment]
Maybe this can help #179

```
    // remove unused nodes
    const getDescendants = (parsedData, nodeId) => {
        const nodes = {}
        function recursiveMap(nodeId) {
            const node = parsedData[nodeId]
            node.nodes.forEach((nodeId) => recursiveMap(nodeId))
            Object.keys(node.linkedNodes).map((key) => {
                const nodeId = node.linkedNodes[key]
                return recursiveMap(nodeId)
            })
            nodes[nodeId] = node
        }
        recursiveMap(nodeId)
        return nodes
    }
```

**Comment by Spenc84** [comment]
Thanks. I guess I can periodically run that on the root node until the issue can get sorted out.

**Comment by prevwong** [comment]
Related to @179
