### ISSUE TITLE
Ability to get code base for Canvas

### ISSUE THREAD

**Issue by schnetzlerjoe** [prevwong/craft.js#231]
**Is your feature request related to a problem? Please describe.**
It is a crucial component to allow end-users to export or have the option to get the code base for their no-code apps. With this ability, I cannot see a reason on why someone would not use CraftJS. Just an idea.

**Describe the solution you'd like**
The ability to export or view the codebase in a canvas naturally built into CraftJS.

**Comment by TheGrimSilence** [comment]
So as far as I know, you're hoping for something similar to Webflow. You can design everything without touching code, but when you save the project, Webflow renders to HTML and saves everything to their CDN and hosting. However, you're able to also "Export to Code" manually for taking your project elsewhere (if you have the right plan). What I can imagine is happening, is that per page, you just transpile everything into their correct files. HTML, minified JS, minified CSS, assets, etc. 

This is "Out of the scope" of this project as others have asked this very question. But that's pretty much what you're looking at. It's implementation is up to you. I recommend saving the state of a page in a NoSQL DB and listen to events. As far as exporting you could just walk the tree, or you could maybe bootstrap Webpack 5 with some plugins to generate everything you need.

**Comment by schnetzlerjoe** [comment]
@TheGrimSilence Gotcha! Thank you much for your response. I have came up with a solution with your advice. I can just extract the tree structure and I'm building a compiler to just take that and compile it into React. Hopefully it comes out good!

**Comment by TheGrimSilence** [comment]
@schnetzlerjoe happy to help! Could you let me see your solution when you get a chance?

**Comment by schnetzlerjoe** [comment]
@TheGrimSilence Yes. Sure! I will open source it. Maybe could be a plugin for Craft.
