### ISSUE TITLE
Expose query.parseReactElement outside React component context, e.g. for unit tests

### ISSUE THREAD

**Issue by antoineol** [prevwong/craft.js#235]
### Is your feature request related to a problem? Please describe.

I'm trying to implement unit tests on business logic that is processing a craftjs node tree, generated earlier from JSX. The app uses a very nice utility, `query.parseReactElement(jsx)`. But it requires a `query` objet which I don't have in a unit test outside React components. `parseReactElement` doesn't seem to be importable.

I tried to create a fake `query`, but I can't import and use `QueryMethods` which looked like a way to do it.

### Describe the solution you'd like

Is there a way to expose the `parseReactElement` utility? Or give an easy way to create a fake `query` allowing us to use its utilities like `parseReactElement` ?

### Additional context

N/A

Thanks a lot for this great library!

**Comment by prevwong** [comment]
Yeah, this is a good point. The `next` branch exposes the `QueryMethods`, I will add it to the `develop` branch asap!

**Comment by antoineol** [comment]
Thanks a lot! Looking forward to the release :)

**Comment by prevwong** [comment]
Released in 0.1.0-beta.17!
