### ISSUE TITLE
Landing page not explained anywhere

### ISSUE THREAD

**Issue by anakinjay** [prevwong/craft.js#239]
Hey guys,
love the project, just a question and a point of feedback:

The editor on the landing page is what got me hooked.  I went through the tutorial and got the basic editor completed, but now I can't find any documentation to explain how to go from basic editor to what was shown on the landing page.   

Is there anywhere that explains what frameworks were used to create the landing page?  If not could someone fill me in?  And that might be a nice addition to the documentation if it's not there already.

Thank you very much!

**Comment by prevwong** [comment]
Hey @anakinjay 

I agree that the landing page should be documented better, at least in the codebase.

The landing page is based on what was already covered in the basic example/tutorial, just better looking. The main additions in terms of Craft-related work are :-
- The usage of the `@craftjs/layers` package which provides the layers view that you see on the sidebar. (Relevant code [here](https://github.com/prevwong/craft.js/blob/develop/packages/examples/landing/components/editor/Viewport/Sidebar/index.tsx#L43) and docs can be found [here](https://craft.js.org/r/docs/additional/layers))
- The indicators that you get when you hover/select elements. You can achieve this a couple of different ways, but the approach used in the landing example is to render a div via a Portal for each Node, and conditionally display them when the Node is being hovered/selected. Relevant code [here](https://github.com/prevwong/craft.js/blob/develop/packages/examples/landing/components/editor/RenderNode.tsx) and [here](https://github.com/prevwong/craft.js/blob/develop/packages/examples/landing/pages/index.tsx#L60))

Apart from that - it's really just UI work with tailwind, material-ui and styled-components.

**Comment by anakinjay** [comment]
Exactly what I needed to know to at least point me in the right direction, thank you so much!
