### ISSUE TITLE
When stretched diagonally on the left, the block zoomed in or out incorrectly

### ISSUE THREAD

**Issue by Fuyuwei-Fxx** [prevwong/craft.js#252]
When stretched diagonally on the left, the block zoomed in or out incorrectly. I hope the point on the left can follow the drag

https://user-images.githubusercontent.com/39211654/120444154-f1eae000-c3b9-11eb-876d-53fda31e4ff9.mp4

**Comment by prevwong** [comment]
Hi, thank you for opening this issue but this is related to the `re-resizable` react library we're using for the landing example and for now, I believe this is the expected behaviour.
