### ISSUE TITLE
Element‘s ID

### ISSUE THREAD

**Issue by 963542298** [prevwong/craft.js#268]
I want to know the rules for generating IDs，Thanks!

**Comment by ankri** [comment]
Craft [uses](https://github.com/prevwong/craft.js/blob/develop/packages/core/package.json#L42) the package [shortid](https://www.npmjs.com/package/shortid) to generate the ids.

**Comment by ankri** [comment]
By the way thanks for making me look into it, otherwise I wouldn't have seen the warning on the `shortid` page.

**Comment by 963542298** [comment]
Use Nano ID？
