### ISSUE TITLE
Issue with drag and drop components between other components

### ISSUE THREAD

**Issue by hugominas** [prevwong/craft.js#273]
**Describe the bug**
Its not possible to add new canvas items between other placed canvas items

**To Reproduce**

1. On the Landing Page example try placing containers after each other
2. then try and add a new container between them

**Expected behavior**
We should be able to place new components between other placed canvas components, this doesn't happen even when you add margin between them. This is crucial for a website builder, at the moment it either fails or places the new item on the top

**Screenshots**
![Craft js (1)](https://user-images.githubusercontent.com/3314986/124987045-4a09a780-e034-11eb-9d40-9750a8b6ce34.gif)

**Comment by prevwong** [comment]
Interesting, it looks like because the Container is a Canvas node; when you try to drop something in between, it will be placed inside the Container:

<img width="1426" alt="Screenshot 2021-07-09 at 2 05 18 PM" src="https://user-images.githubusercontent.com/16416929/125031108-b8934780-e0be-11eb-8389-5911057c37fe.png">

Will look into it 👍

**Comment by hugominas** [comment]
I tried with flex gap, margin and padding to solve this issues. @troelsfr in Discord posted a solution where he solved it by adding a new item to the DOM before and after the rendered node when the user is dragging. This has solved the issue. His implementation was done at the RenderNode and added 1.5rem height to the div

`  
const [dragging, setDragging] = useState(false);

  useEffect(() => {
    let onDragStart = () => setDragging(true);
    let onDragStop = () => setDragging(false);

    document.addEventListener("dragstart", onDragStart);
    document.addEventListener("dragend", onDragStop);
    return () => {
      document.removeEventListener("dragstart", onDragStart);
      document.removeEventListener("dragend", onDragStop);
    };
  });

 {dragging && <div className="dragSpacer"></div>}
      {render}
 {dragging && <div className="dragSpacer "></div>}
`

going to close this for now as it solved this issue.

![localhost_3003_matrizdesustentabilidade (2)](https://user-images.githubusercontent.com/3314986/125164384-d5488180-e189-11eb-8ff5-75b8829f15cd.gif)

**Comment by hugominas** [comment]
I guess this issue is still present after all, it works and it seems to be related with this [issue](https://github.com/prevwong/craft.js/issues/274).

Everything works fine until you save the stated when you load, no matter where you drop your node it will always be stacked on the top of the tree. @prevwong any pointers on how we could solve this issue.

It looks like we are losing the dnd order of the nodes upon load.

![My page](https://user-images.githubusercontent.com/3314986/125825593-b1980447-d532-4f2e-8ccd-9ea1f4de735f.gif)

**Comment by hugominas** [comment]
Just tested locally and with the basic example everything is working, I guess something is wrong on the example website, closing this issue for now.

**Comment by ostorres-pscu** [comment]
I am encountering a problem with the drag-and-drop feature for elements. Users can drag and drop, but the line indicator malfunctions when dragging an element towards the bottom. Specifically, it does not indicate correctly at a certain point, skipping over elements and suggesting a drop either after the skipped elements or before them.
