### ISSUE TITLE
TypeError: Cannot assign to read only property 'parent' of object '#<Object>' : React Javascript

### ISSUE THREAD

**Issue by throne1986** [prevwong/craft.js#277]
I was using v16 now I updated with v19 when I run the app I get this error

`TypeError: Cannot assign to read only property 'parent' of object '#<Object>'` 

I have seen similar error but with people using typescript 

Here is the full error

![screencapture-localhost-3000-2021-07-20-14_24_51](https://user-images.githubusercontent.com/27904724/126323515-b5f25d0f-783e-4bb1-912a-22b02ae28b84.png)

any solution?

**Comment by rishii1909** [comment]
I've been struggling with the same issue for around 2 days now...

**Comment by throne1986** [comment]
me its a third day and I cant figure out the problem :(

**Comment by rishii1909** [comment]
It has been resolved for me just now, a few mins ago, reverting the version to @craftjs/core@0.1.0-beta.17 and making a few changes to the code did the job for me. Perhaps I can help you out?

**Comment by throne1986** [comment]
> It has been resolved for me just now, a few mins ago, reverting the version to @craftjs/core@0.1.0-beta.17 and making a few changes to the code did the job for me. Perhaps I can help you out?

what did you change?  I am using v17 but still the same

**Comment by rishii1909** [comment]
Can you please show your code, and let me know if it's partially working as of now, or totally non-functional. I'll compare it with what I have and tell you what might work.

**Comment by throne1986** [comment]
> Can you please show your code, and let me know if it's partially working as of now, or totally non-functional. I'll compare it with what I have and tell you what might work.

Hi I have created a repo here : https://github.com/throne1986/sample_app   please help

**Comment by ibosev** [comment]
I tried to run the basic example and I had similar issue with v19. Seems the problem is with the Card component in the example. When you comment it out, it is all good. Still cannot see the problem in the component though

**Comment by throne1986** [comment]
@prevwong does this mean the error is fixed or we should wait? thanks
