### ISSUE TITLE
TypeError: query.serialize is not a function

### ISSUE THREAD

**Issue by seananth** [prevwong/craft.js#278]
Been following the basic tutorial and i'm on the last step adding the top bar but i can't get past this error, i'm not sure whats going on. 

I've tried this on 2 projects but i get the same error everytime i try to console.log(query.serialize())

**Comment by seananth** [comment]
<img width="649" alt="typeError" src="https://user-images.githubusercontent.com/58331443/126509555-269fd41b-3f82-4964-921e-1b9e14650205.PNG">

**Comment by hugominas** [comment]
Hi @seananth is your TopBar component child of your Editor? I think this has happen to me before when I was moving components around the editor.

**Comment by seananth** [comment]
@hugominas omg that was it! thank you so much, been trying to figure this out all day..
