### ISSUE TITLE
No props on dragged components

### ISSUE THREAD

**Issue by WeH1D** [prevwong/craft.js#291]
When user component is dragged and dropped into container, and its children props are logged, we can see that no props are available to us except the "key" prop. This isn't the case with components that are manually added into the container.

For example:

If we log children of a drag & dropped Video component we can't see any props listed

The component:
<img width="664" alt="Screenshot 2021-08-05 at 16 31 05" src="https://user-images.githubusercontent.com/29353608/128368941-5f651830-888a-473b-8999-ed11ff243c06.png">
The log:
<img width="402" alt="Screenshot 2021-08-05 at 16 31 48" src="https://user-images.githubusercontent.com/29353608/128368970-24b258c3-7619-40e9-be07-f335255845a0.png">

But if we add the video component manually with the same props listed, then we can see  the children props in log

The component:
<img width="661" alt="Screenshot 2021-08-05 at 16 29 58" src="https://user-images.githubusercontent.com/29353608/128369176-d6c8813d-22f3-4f92-9d54-50afde7269f4.png">

The log:
<img width="426" alt="Screenshot 2021-08-05 at 16 29 21" src="https://user-images.githubusercontent.com/29353608/128369238-5e5eefe2-65ef-4649-838e-368dbba35709.png">

As you can see, when the component has children that are manually added, we can see their props ("videoId", "height"). But when we drag and drop the same component with the same props listed in the Toolbox create func, then no props are listed in the log except the "key" prop.

Is this normal behaviour  and is there a way for us to access the child props (read them not edit them) of a component that has been dragged and dropped?

**Comment by ankri** [comment]
Hi, could you please post your code for the Video component?

I created a simple [codesandbox](https://codesandbox.io/s/gifted-williamson-liznd?file=/components/user/Video.js) which shows that the props passed to the component in `create`.

It would be great if you could fork the codesandbox and add your code of the video component.

**Comment by WeH1D** [comment]
@ankri  Thanks for your fast reply.

Our problem is that when we drop a video component in the container (so the video component becomes a child of the container), and we try to read the props of children from the container,  we recieve empty props.

In this case (container that recieves a dropped video component):

<img width="688" alt="Screenshot 2021-08-05 at 17 32 48" src="https://user-images.githubusercontent.com/29353608/128378591-002bc198-1e85-4e1c-9aa8-d6558eb6b488.png">

the log shows no props for the children(video component).

But if we add the video component manually to the container, then the log shows its props. For example:

<img width="661" alt="Screenshot 2021-08-05 at 16 29 58" src="https://user-images.githubusercontent.com/29353608/128378823-af5ff1cb-0473-4ebe-8423-83613e547a27.png">

**Comment by ankri** [comment]
Ah. I see! I totally misread your first post, my bad.

I updated the [codesandbox](https://codesandbox.io/s/gifted-williamson-liznd?file=/components/user/Container.js) with a workaround for you.

**Comment by WeH1D** [comment]
> Ah. I see! I totally misread your first post, my bad.
> 
> I updated the [codesandbox](https://codesandbox.io/s/gifted-williamson-liznd?file=/components/user/Container.js) with a workaround for you.
> 
> ```js
>   const {
>     connectors: { connect, drag },
>     id
>   } = useNode();
> 
>   const { propsOfChildren } = useEditor((state, query) => {
>     const descendants = query.node(id).descendants();
> 
>     return {
>       propsOfChildren: descendants.map((id) => query.node(id).get().data.props)
>     };
>   });
> 
>   console.log(propsOfChildren);
> ```

Thank you soo much, it worked like a charm
This is exactly what we needed.

**Comment by ankri** [comment]
> This is exactly what we needed.

Glad to hear. Can we close this issue, or do you have another question regarding this issue?

**Comment by WeH1D** [comment]
> > This is exactly what we needed.
> 
> Glad to hear. Can we close this issue, or do you have another question regarding this issue?

No further questions, this solved exactly what we needed. Thank you very much for the help, you are amazing!
