### ISSUE TITLE
Enable selector box in the right panel while selecting a particular component on the canvas

### ISSUE THREAD

**Issue by ProPhycient5** [prevwong/craft.js#294]
When the user click on that component on the canvas, at the same time, we get few setting components like Typography, Margin, Appearance in right panel under Customization. But If I want to show that same name of the draggable component (like 'Text' or 'Container')that I clicked on the canvas, How can I do that ????

Below is the default code, that is used in order to enable of rendering corresponding setting component of a particular draggable component like Typography, Margin, etc.
What I need to add in order to enable a feature so that name of the clicked or selected component appears on the top of right panel. Please help me to enable this feature.

```
import React from 'react';
import { useEditor } from '@craftjs/core';
export * from './ToolbarItem';
export * from './ToolbarSection';
export * from './ToolbarTextInput';
export * from './ToolbarDropdown';
export * from './ToolbarFontInput';

export const Toolbar = () => {
  const { active, related } = useEditor((state) => ({
    active: state.events.selected,
    related:
      state.events.selected && state.nodes[state.events.selected].related,
  }));

  return (
    <div className="py-0 h-screen">
      {active && related.toolbar && React.createElement(related.toolbar)}
      {!active && (
        <div
          className="px-5 py-2 flex flex-col items-center h-full justify-center text-center"
          style={{
            color: 'rgba(255, 255, 255, 1)',
            fontSize: '11px',
          }}
        >
          <h2 className="pb-1 ">Click on a component to start editing.</h2>
          <h2 className="">
            You could also double click on the layers below to edit their names,
            like in Photoshop
          </h2>
        </div>
      )}
    </div>
  );
};



```

**Comment by ankri** [comment]
Hi!

I'm not sure whether I understand you correctly. Do you want to display the component's name in the Editor/Canvas, like this (ComplexSection)?
![image](https://user-images.githubusercontent.com/2842920/129341007-92f42e99-043a-43e3-8135-7c5bf1a75a89.png)
Taken from the landing page example from [craft.js.org](https://craft.js.org)

This is achieved by rendering a floating box in [RenderNode.tsx](https://github.com/prevwong/craft.js/blob/develop/examples/landing/components/editor/RenderNode.tsx#L113)

**Comment by ankri** [comment]
> What I need to add in order to enable a feature so that name of the clicked or selected component appears on the top of right panel. Please help me to enable this feature.

The top right of which panel? Because in the basic example the component name is displayed in the top right:

![image](https://user-images.githubusercontent.com/2842920/129341504-1f9e7fa1-d066-411f-a291-b497e10f999d.png)

See: Selected Button on the top right of the SettingsPanel. The corresponding code is [here](https://github.com/prevwong/craft.js/blob/develop/examples/basic/components/SettingsPanel.js#L38-L48)

**Comment by ProPhycient5** [comment]
Thank you Andy Krings-Stern for your kind response. Yes, I was able to enable that feature for showing name and displayName. But on the top of the that I want showing corresponding icons to a particular selected component. 
how will I able to show corresponding icons beside component name ?????
I wanted to know where can I pass or store these svg icons or objects, although I know that name, displayName, type are coming by default from Craft.js 
If you are in craftjs discord, I can send you screenshot of a pic, which will help for better understanding.

**Comment by ProPhycient5** [comment]
Please reply to above query.

**Comment by prevwong** [comment]
@ProPhycient5 Your question in this issue has been answered.

Your second question is unrelated to what you were asking for originally. Regardless, I've already replied to that same question that you posted on Discord as well.
