### ISSUE TITLE
The UseEditor state events has changd from simple string to Set<string> for events

### ISSUE THREAD

**Issue by pksorensen** [prevwong/craft.js#295]
**Describe the bug**
I was following the code examples from the examples of the repository to find that the settings panel did not work. 

however when i cloned the project and build the example, it worked.

I found out that its because my own project used a later version of craftjs which has changed editor state events from string to Set<string>

![image](https://user-images.githubusercontent.com/2718591/129479195-e3a3406e-0684-41ac-9b8e-4e00f63c1dc3.png)

I dont think this is reflected in the documentation ? - i am new to the project and I might just have missed it.  Atleast i wanted to drop this here for others that might run in same problem

**Comment by prevwong** [comment]
Hey @pksorensen, what version of Craft are you using? This change to the `events` property is only on the next branch (version 0.2.x onwards).

**Comment by pksorensen** [comment]
i used latest version from npm - i am experimenting and made a editor and want to be on bleeding edge.

![pagedesigner](https://user-images.githubusercontent.com/2718591/129529155-6cf182f9-306f-41d8-90b6-e709638c8818.gif)

**Comment by rohailtaha** [comment]
I have the same issue, I am using @craftjs/core version "^0.2.0-beta.3". 
The **Basic Tutorial** in the doumentation have this section of code:
    ```
const currentNodeId = state.events.selected;
    let selected;

    if ( currentNodeId ) {
      selected = {
        id: currentNodeId,
        name: state.nodes[currentNodeId].data.name,
        settings: state.nodes[currentNodeId].related && state.nodes[currentNodeId].related.settings
      };
    }
```
The above code is expecting **state.events.selected** to be string, but it is rather a set. The documentation should reflect the change.

**Comment by Devmindtk** [comment]
I am using @craftjs/core version "^0.2.0-beta.12" and it throws an error :
"TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method."

const SettingsPanel = (props) => {
  const { actions, selected }  = useEditor((state, query) => {
    const [currentNodeId]= state.events.selected;
    let selected;
    if ( currentNodeId ) {
      selected = {
        id: currentNodeId,
        name: state.nodes[currentNodeId].data.name,
        displayName : state.nodes[currentNodeId].data.displayName,
        settings: state.nodes[currentNodeId].related && state.nodes[currentNodeId].related.settings,
        isDeletable: query.node(currentNodeId).isDeletable()
      };
      props.returnSelectedValue(true)
    }else{
      props.returnSelectedValue(false)
    }

    return {
      selected
    }
  });

please check the above code and let me know how I can resolve this issue.
