### ISSUE TITLE
In the landing example,if set the container's default width = "100",drag container between two Containers has no effect

### ISSUE THREAD

**Issue by linxianxi** [prevwong/craft.js#306]
@prevwong 
1、set the container default width is 100%.

2、Drag two containers on the page.

3、Releasing the mouse in the first place works, but not in the second place.
![image](https://user-images.githubusercontent.com/47104575/132850852-20e77945-f26f-4bff-b158-40396740f58c.png)

**Comment by hugominas** [comment]
@linxianxi I believe this has been fix in this pull request  https://github.com/prevwong/craft.js/pull/300 you just need to wait until it gets merge into the branch your using

**Comment by linxianxi** [comment]
> @linxianxi I believe this has been fix in this pull request #300 you just need to wait until it gets merge into the branch your using

OK. If I set `marginBottom=10px` to container,it works.

**Comment by hugominas** [comment]
yes, this issue was reported a few months ago https://github.com/prevwong/craft.js/issues/273 you can find a workaround in the meantime

**Comment by linxianxi** [comment]
> #273



> yes, this issue was reported a few months ago #273 you can find a workaround in the meantime

Oh, thanks, I will wait it.

**Comment by hugominas** [comment]
Great @linxianxi I think it might help out @prevwong if you close this issue for now :)
