### ISSUE TITLE
How do I save a node as a template that I can drag into the editor

### ISSUE THREAD

**Issue by linxianxi** [prevwong/craft.js#316]
**Describe the solution you'd like**
save a node as a template that I can drag into the editor

Something like #209 needs to regenerate the ID of each node. But how do I save it in the sidebar and drag it?

The second parameter can now only be ReactElement, and it should be possible to customize the NodeTree type
```
connectors.create(
    ref,
    <Element />
  )
```
should like this
```
connectors.create(
    ref,
    // executed at the start of each drag to generate a new id for each node
   () => {
        const nodeTree = ...;
        const newNodeId = getRandomId();
        ......
        return nodeTree;
    }
  )
```

**Comment by hugominas** [comment]
@linxianxi I have an open issue with this https://github.com/prevwong/craft.js/issues/311 I got stuck on the node serializations which I can't access from the available actions. Its only possible to serialize the state. prob @prevwong could point us in the correct direction.

**Comment by linxianxi** [comment]
> @linxianxi I have an open issue with this #311 I got stuck on the node serializations which I can't access from the available actions. Its only possible to serialize the state. prob @prevwong could point us in the correct direction.

Maybe we can do it ourselves with these two methods in the source code?
![image](https://user-images.githubusercontent.com/47104575/135008095-7eb3d257-3845-4304-8436-e8ad50ea5238.png)

**Comment by hugominas** [comment]
Yes, that's correct path. You need to clone the tree, so that you have new IDs, I did try serializing but it didn't work for me I guess it needs to be recursive to take care of all the child nodes and child of does child nodes. 

It would be great if we could reuse the internal method https://github.com/prevwong/craft.js/blob/3156043232b7e88f39e313b70f00bfb91ba830a3/packages/core/src/utils/serializeNode.tsx#L15 I will try rewriting the method for testing as soon as I have time

**Comment by linxianxi** [comment]
@hugominas Of course, you need to traverse all nodes, childrens, and parents. If have the same ID, you need to generate a new ID to replace them

**Comment by hugominas** [comment]
Almost got it working, https://github.com/prevwong/craft.js/issues/311#issuecomment-929317924

**Comment by linxianxi** [comment]
@hugominas This example can save the template anywhere you want, but you can't drag it from the sidebar to the editor yet, maybe when my PR passes.

```
// import { getRandomId } from "@craftjs/utils";

const fromEntries = (pairs) => {
  if (Object.fromEntries) {
    return Object.fromEntries(pairs);
  }
  return pairs.reduce(
    (accum, [id, value]) => ({
      ...accum,
      [id]: value,
    }),
    {}
  );
};

const getCloneTree = useCallback(
  (tree: NodeTree) => {
    const newNodes = {};
    const changeNodeId = (node: Node, newParentId?: string) => {
      const newNodeId = getRandomId();
      const childNodes = node.data.nodes.map((childId) =>
        changeNodeId(tree.nodes[childId], newNodeId)
      );
      const linkedNodes = Object.keys(node.data.linkedNodes).reduce(
        (acc, id) => {
          const newLinkedNodeId = changeNodeId(
            tree.nodes[node.data.linkedNodes[id]],
            newNodeId
          );
          return {
            ...acc,
            [id]: newLinkedNodeId,
          };
        },
        {}
      );

      let tmpNode = {
        ...node,
        id: newNodeId,
        data: {
          ...node.data,
          parent: newParentId || node.data.parent,
          nodes: childNodes,
          linkedNodes,
        },
      };
      let freshNode = query.parseFreshNode(tmpNode).toNode();
      newNodes[newNodeId] = freshNode;
      return newNodeId;
    };

    const rootNodeId = changeNodeId(tree.nodes[tree.rootNodeId]);
    return {
      rootNodeId,
      nodes: newNodes,
    };
  },
  [query]
);

// to save as a template
const handleSaveTemplate = useCallback(() => {
  const tree = query.node(id).toNodeTree();
  const nodePairs = Object.keys(tree.nodes).map((id) => [
    id,
    query.node(id).toSerializedNode(),
  ]);
  const serializedNodesJSON = JSON.stringify(fromEntries(nodePairs));
  const saveData = {
    rootNodeID: tree.rootNodeId,
    nodes: serializedNodesJSON,
  };
  // save to your database
  localStorage.setItem("template", JSON.stringify(saveData));
}, [handleAdd, id, query]);

// add templates where you want
const handleAdd = useCallback(() => {
 // get the template from your database
  const data = JSON.parse(localStorage.getItem("template"));
  const newNodes = JSON.parse(data.nodes);
  const nodePairs = Object.keys(newNodes).map((id) => {
    let nodeId = id;

    return [
      nodeId,
      query
        .parseSerializedNode(newNodes[id])
        .toNode((node) => (node.id = nodeId)),
    ];
  });
  const tree = { rootNodeId: data.rootNodeID, nodes: fromEntries(nodePairs) };
  const newTree = getCloneTree(tree);

  // add templates where you want
  actions.addNodeTree(newTree, ROOT_NODE, 0);
}, [actions, getCloneTree, query]);
```

**Comment by hugominas** [comment]
Awesome, I will test it! thanks for your help

**Comment by hugominas** [comment]
Just tested and its working :D its a better solution to save the template in localstorage then copy and pasting the hash!

I added to icons to the RenderNode component to be able to copy and paste. 

I had to add a timeout to refresh the sate

```
    setTimeout(function () {
        actions.deserialize(query.serialize());
        actions.selectNode(newTree.rootNodeId);
      }, 100);
```

**Comment by linxianxi** [comment]
@hugominas I don't know why I don't need to set setTimeout to select a node

**Comment by hugominas** [comment]
I will test it again, but the state was not updating after copying into a node Id

**Comment by hugominas** [comment]
Sorry my bad, it works correctly without the setTimeout. Glad you opened a PR this should should be present everywhere in craft, layers setting. 

Thanks for your help

**Comment by Spenc84** [comment]
We've also found ourselves in the same position where we need a way to replicate a node tree using the drag and drop functionality. It would be really helpful if the second argument of the create method could be a callback function that returns the desired node or node tree that should get added to the layout like you suggested in your original post.

The code you listed just above seems like it would be an adequate solution if the id of the desired rootNode and desired index are already known, but if the goal is to allow a user to drag something from a sidebar to where they want it to be on the layout then I'm at a loss. Unless I've missed something, Craft doesn't seem to provide any way to identify what the parent node and index should be based off of the mouse coordinates?

**Comment by hugominas** [comment]
We have used this solution to allow for copy and paste node trees into other node trees. So a simple local storage solution works fine. If you want to create a component out of that tree you would need to store the value in a db and then present it as a user componente, so that you can drag it in. 

Hope this helps, it would be a great way to have custom nodes create on the fly so let me know if you where able to do it :)

**Comment by Spenc84** [comment]
It's a bit janky but until linxianxi's PR goes through we've decided to implement a draggable button that uses craft's create method to add a simple empty div to the drop location and then uses the create method's optional callback to determine what the newly added div's index and parent id will be. We then delete that node, replicate the node tree of whatever node is actively selected in state.events.selected, update the id's and use the addNodeTree method to add the replicated tree to the parent id and index of div node we just deleted. The client won't ever see the temporary div and we're using the history throttle method to ensure that it's all done as a single step in the history log.

While we would certainly appreciate a more flexible create method, this has actually been working out pretty well for us so far.

**Comment by prevwong** [comment]
#317 Released in 0.2.0-beta.2 🎉

**Comment by ylnsnv** [comment]
Can anyone provide an example of how to use this? Unfortunately, the documentation appears to be outdated, and I haven't found a way to update it. I'm working with a Craft.js editor where users can create their own elements. I want them to be able to drag and drop these elements onto other editors, essentially creating components for use within the application. However, I'm struggling to make this work. Could anyone offer any guidelines or advice?

**Comment by xs-nayeem** [comment]
@linxianxi did you implement drag feature on serialized JSON?

**Comment by linxianxi** [comment]
> @linxianxi @Spenc84 did you implement drag feature on serialized JSON? Is there any working example of do I implement this?

sorry, I don't remember, I haven't used the library in over two years, try this pr https://github.com/prevwong/craft.js/pull/317

**Comment by linxianxi** [comment]
> > > @linxianxi @Spenc84 did you implement drag feature on serialized JSON? Is there any working example of do I implement this?
> > 
> > 
> > sorry, I don't remember, I haven't used the library in over two years, try this pr #317
> 
> I have checked this PR. Couldn't really figure out how to implement this? ![image](https://private-user-images.githubusercontent.com/106504976/300399469-f58fb6f2-ab76-499a-8025-29500c8c461e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODQwODUsIm5iZiI6MTcwNjU4Mzc4NSwicGF0aCI6Ii8xMDY1MDQ5NzYvMzAwMzk5NDY5LWY1OGZiNmYyLWFiNzYtNDk5YS04MDI1LTI5NTAwYzhjNDYxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwMzAzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWZjZGY5NGU3OGJmODYwOWY5NWQyNzhiYmM4NDQ1YTQ0ZDNkYjE4YmZiOWNjZTk2NDE2OTQ3NzMyNjJkNGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6DkOG2WAkADNLQu0SjoOwwqhNbY_i1-llFLl70-JRas) Any kind of insight will be really helpful.

run this repo and view code https://github.com/linxianxi/page-builder

**Comment by MimMostakim** [comment]
Thanks for this repo. It works fine for single node. I can drag the single node from sidebar. But when I loop through multiple nodes, it does not work. Looking for some suggestion to drag multiple node at once.

**Comment by xs-nayeem** [comment]
> > > > @linxianxi @Spenc84 did you implement drag feature on serialized JSON? Is there any working example of do I implement this?
> > > 
> > > 
> > > sorry, I don't remember, I haven't used the library in over two years, try this pr #317
> > 
> > 
> > I have checked this PR. Couldn't really figure out how to implement this? ![image](https://private-user-images.githubusercontent.com/106504976/300399469-f58fb6f2-ab76-499a-8025-29500c8c461e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODQwODUsIm5iZiI6MTcwNjU4Mzc4NSwicGF0aCI6Ii8xMDY1MDQ5NzYvMzAwMzk5NDY5LWY1OGZiNmYyLWFiNzYtNDk5YS04MDI1LTI5NTAwYzhjNDYxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwMzAzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWZjZGY5NGU3OGJmODYwOWY5NWQyNzhiYmM4NDQ1YTQ0ZDNkYjE4YmZiOWNjZTk2NDE2OTQ3NzMyNjJkNGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6DkOG2WAkADNLQu0SjoOwwqhNbY_i1-llFLl70-JRas) Any kind of insight will be really helpful.
> 
> run this repo and view code, this is code from two years ago https://github.com/linxianxi/page-builder

Tried your code. It works fine for a single node. I have also checked the source. It seems that it does not support for multiple nodes. Do craft js supports multiple node drag at once?

**Comment by hugominas** [comment]
I am sharing an util function that takes a saved serialized node at the moment is from localstorage but you can enhance it to read it from db.

The serialized node looks something like this:

`{
  rootNodeID: tree.rootNodeId,
  nodes: serializedNodesJSON,
};`


How to use it
`
import { copyNodeTree, pasteNodeTree } from "./util";
....
<Copy
  onClick={(e) => {
    e.preventDefault();
    copyNodeTree(id, query);
  }}
/>
...
<Paste
    onClick={(e) => {
      e.preventDefault();
      pasteNodeTree(id, query, actions, node); //show pass the template when connected to a db
    }}
  />
`


The code in util.js
`import { getRandomId } from "@craftjs/utils";
/**
 * Handle copy and past nodes
 */
const fromEntries = (pairs) => {
  if (Object.fromEntries) {
    return Object.fromEntries(pairs);
  }
  return pairs.reduce(
    (accum, [id, value]) => ({
      ...accum,
      [id]: value,
    }),
    {}
  );
};
// to copy a node
const getCloneTree = (node, query, tree) => {
  const newNodes = {};
  const changeNodeId = (node, newParentId) => {
    const newNodeId = getRandomId();
    const childNodes = node.data.nodes.map((childId) =>
      changeNodeId(tree.nodes[childId], newNodeId)
    );
    const linkedNodes = Object.keys(node.data.linkedNodes).reduce((acc, id) => {
      const newLinkedNodeId = changeNodeId(
        tree.nodes[node.data.linkedNodes[id]],
        newNodeId
      );
      return {
        ...acc,
        [id]: newLinkedNodeId,
      };
    }, {});

    let tmpNode = {
      ...node,
      id: newNodeId,
      data: {
        ...node.data,
        parent: newParentId || node.data.parent,
        nodes: childNodes,
        linkedNodes,
      },
    };
    let freshNode = query.parseFreshNode(tmpNode).toNode();
    newNodes[newNodeId] = freshNode;
    return newNodeId;
  };

  const rootNodeId = changeNodeId(tree.nodes[tree.rootNodeId]);
  return {
    rootNodeId,
    nodes: newNodes,
  };
};

// to save as a template
export const copyNodeTree = (id, query) => {
  const tree = query.node(id).toNodeTree();
  const nodePairs = Object.keys(tree.nodes).map((id) => [
    id,
    query.node(id).toSerializedNode(),
  ]);
  const serializedNodesJSON = JSON.stringify(fromEntries(nodePairs));
  const saveData = {
    rootNodeID: tree.rootNodeId,
    nodes: serializedNodesJSON,
  };
  // save to your database
  localStorage.setItem("template", JSON.stringify(saveData));
};

// add templates where you want
export const pasteNodeTree = (id, query, actions, node) => {
  // get the template from your database
  const data = JSON.parse(localStorage.getItem("template"));
  console.log("data", data);
  const newNodes = JSON.parse(data.nodes);
  const nodePairs = Object.keys(newNodes).map((id) => {
    let nodeId = id;

    return [
      nodeId,
      query
        .parseSerializedNode(newNodes[id])
        .toNode((node) => (node.id = nodeId)),
    ];
  });
  const tree = {
    rootNodeId: data.rootNodeID,
    nodes: fromEntries(nodePairs),
  };
  const newTree = getCloneTree(node, query, tree);
  // add templates where you want
  actions.addNodeTree(newTree, id, 0);
  // actions.selectNode(newTree.rootNodeId);

  // setTimeout(function () {
  //   actions.deserialize(query.serialize());
  actions.selectNode(newTree.rootNodeId);
  // }, 100);
};
`
