### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by Delwalt** [prevwong/craft.js#324]
Hi Craft js team,
I have been using your lib and its awesome.

I noticed one bug and wanted to point out.
So in the ` useEditor()` api documentation, one link is broken.
I am attaching screenshot for the reference. 

<img width="1432" alt="Screenshot 2021-10-01 at 10 56 01 AM" src="https://user-images.githubusercontent.com/7600235/135569943-95479bfe-5e8f-407e-8360-a07cad5227d2.png">

**Comment by MohamedHakem** [comment]
Hi @Delwalt, Thank you for reporting this. This is no longer an issue, the link sends you to the NodeHelpers under API Reference section:  https://craft.js.org/docs/api/helpers/
