### ISSUE TITLE
node.events.dragged does not work.

### ISSUE THREAD

**Issue by velikayikci** [prevwong/craft.js#329]
Hello,

    const {
        dragged
    } = useNode((node) => ({
        dragged: node.events.dragged
    }));

dragged prop is allways false.

How can I select the component after component dragged ?

**Comment by ankri** [comment]
You mean after creating the component?

```js
const { connectors, actions } = useEditor();

connectors.create(ref, node, {
  onCreate: (nodeTee) => {
    actions.selectNode(nodeTee.rootNodeId);
  },
});
```

---
`dragged` not working is related to #321
