### ISSUE TITLE
Immer: Maximum call stack size exceeded when a prop has circular references

### ISSUE THREAD

**Issue by antoineol** [prevwong/craft.js#334]
**[Reproduction on Codesandbox here](https://codesandbox.io/s/craftjs-issue-custom-props-dbqk8?file=/src/App.js)**

**Describe the bug**

When:

- programmatically adding nodes to the tree (`actions.addNodeTree`)
- with a component that has a prop with circular dependencies (which happens in my project for a reason: I need context with complex objects accessible from each component)

Then adding the node fails with an error like:

```
Maximum call stack size exceeded

https://dbqk8.csb.app/node_modules/immer/dist/immer.esm.js:203:17
https://dbqk8.csb.app/node_modules/immer/dist/immer.esm.js:187:63
...
```

I'm pretty sure it used to work in the beta 17, by the time it was released. Currently, I can't reproduce the previous (working) behavior, maybe because of relaxed constraints on indirect dependencies, e.g. between the different craftjs packages or other dependencies (immer?). E.g. now you would get @craftjs/core@beta-17 using @craftjs/utils@beta-20.

**To Reproduce**

In the above codesandbox, check especially this part:

```js
  const jsx = createElement(
    "h2",
    {
      // /!\ Circular references are passed to the props (expected)
      // TODO comment it to remove the error.
      someProp: objectWithCircularReferences
    },
    ...
```

When the line with `someProp: ...` is commented, it works. With this prop, it fails.

**Expected behavior**

It should render without errors.

**Additional context**

Currently, the issue is reproduced on codesandbox with all those versions:

- 0.2.0-alpha.28
- 0.1.0-beta-20
- 0.1.0-beta-17

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | 0.1.0-beta.20
| React            | 17.0.2
| TypeScript       | 4.4.2
| Browser          | Chrome latest version
| npm/Yarn         |1.22.17
| Operating System | Windows with WSL2

**Comment by prevwong** [comment]
This seems to be a limitation with Immer: https://immerjs.github.io/immer/pitfalls/#immer-only-supports-unidirectional-trees

In any case, for the time being - I don't think it makes a lot of sense to be able to support cyclic references in any part of a Craft node since it's not possible for us to preserve that reference when we attempt to serialise/deserialise the `EditorState`.
