### ISSUE TITLE
when i update <Frame /> component data props, i want to my draw content update 

### ISSUE THREAD

**Issue by 963542298** [prevwong/craft.js#338]
i konw changes to these props will have no effect. i change data props, in fact, i want the draw borad  will update. i want to know how to update my draw borad , and i dont want to use deserialize method.

thanks!!!

**Comment by ankri** [comment]
There is a draft PR #191 - maybe you find some hints in the related discussion

**Comment by 963542298** [comment]
i read issue 190, but i want to change json string and render the <Frame data={json} />

**Comment by 963542298** [comment]
i read issue 190, but i want to change json string and then render the '<Frame data={json} />'

**Comment by 963542298** [comment]
i read issue 190, but i want to change json string and render the ```<Frame data={json} />``` Component,

**Comment by ankri** [comment]
So. Why don't you want to use the deserialize method?

You could render a Custom Component (not UserComponent) and call deserialize on it as soon as the props change.

something like this:
```jsx
<Editor>
  <CustomDeserializer data={jsonValue} />
  <Frame>
   ...
  </Frame>
</Editor>
```

```jsx
const CustomDeserializer = ({ jsonValue }) => {
  const { actions } = useEditor();
  useEffect(() => {
    actions.deserialize(jsonValue);
  }, [jsonValue);
  return null;
}
```

**Comment by 963542298** [comment]
now，i try to use deserialize method and i want to know how to clear my component history, because i dont want to craft can 
call redo or undo.

**Comment by ankri** [comment]
```jsx
const CustomDeserializer = ({ jsonValue }) => {
  const { actions } = useEditor();
  useEffect(() => {
    actions.history.clear();
    actions.deserialize(jsonValue);
  }, [jsonValue);
  return null;
}

```

**Comment by 963542298** [comment]
ok, thanks!!!

**Comment by ankri** [comment]
Closing. Let me know if you have any more questions.

**Comment by scdigitalmedia** [comment]
I'm having a similar issue when trying to change the json through getserversideprops. 

Error: Invariant failed: Node does not exist, it may have been removed

I'm running NextJs, and i have a [...slug].tsx page that captures the url in getserverside props, which returns the corresponding page from the database, then I have a useEffect that triggers on the 'page' variable that decodes and decompresses the content into json, i then setJson via usestate that feeds into<CustomDeserializer data={json} /> and  <Frame data={json}>. When I use NextJs' <Link> to navigae between the dynamic pages, i randomly get the above error. I'm not exactly sure what triggers it yet, so I'm having a hard time finding a solution.
