### ISSUE TITLE
Conflicting peer dependency of core is react 16, but it requires 17

### ISSUE THREAD

**Issue by RoyHP** [prevwong/craft.js#356]
**Describe the bug**
See the attached screenshot - I am unable to install CraftJS core 0.2.0 beta0 because it requires a peer dependency of react 16 even though it requires and I am using react 17. Is there a reason it can't just use the same react version of 17?

**To Reproduce**

1. Using @craftjs/core 0.2.0 beta 0 in a project
2. Install with NPM

**Expected behavior**

**Screenshots**
<img width="596" alt="Screen Shot 2021-12-14 at 10 39 30 AM" src="https://user-images.githubusercontent.com/1066439/146030706-dbc983c7-e444-49aa-a25a-911f20ebca62.png">
<img width="721" alt="Screen Shot 2021-12-14 at 10 48 42 AM" src="https://user-images.githubusercontent.com/1066439/146031818-5fef7cf6-9721-4586-8153-6b3e5d2bada8.png">

**Additional context**
Let me know if I can help.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | 0.2.0beta0
| React            | 17
| TypeScript       |
| Browser          |
| npm/Yarn         | npm
| Operating System | macos 12 Monterey on Apple Silicon

**Comment by chrisribal** [comment]
Same problem here.

**Comment by prevwong** [comment]
Fixed in 0.2.0-beta.1 💯
