### ISSUE TITLE
Broken API Reference / Docs / Core Concepts

### ISSUE THREAD

**Issue by OrelVaizman** [prevwong/craft.js#370]
**Describe the bug**
None of the links that appear at the Github repo of Craft.JS works. They all broken.

**To Reproduce**

1. Go to (Repo Link) (https://github.com/prevwong/craft.js/
2. Click on any of the links (docs, API Reference etc.)
3. You'll find out the links are all broken.

**Comment by OrelVaizman** [comment]
Great. Also Broken at NPM page - for your notice..

**Comment by prevwong** [comment]
Fixed
