### ISSUE TITLE
<Editor enabled={false} doesn't disable dragging

### ISSUE THREAD

**Issue by Shaddix** [prevwong/craft.js#373]
**Describe the bug**
If I try to disable `Editor` by setting it's `enabled` prop to `false`, the Editor is still editable. (`<Editor enabled={false}> ... </Editor>`)
Disabling via `actions.setOptions((options) => (options.enabled = false));` works without issues.

**Expected behavior**
`<Editor enabled={false} />` should make elements within editor non-draggable (as it was in 0.1.0-beta.20)

Issue is present in 0.2.0-beta.2.
Issue is not present in 0.1.0-beta.20.

**Comment by gidich** [comment]
Seeing same issue as @Shaddix

**Comment by Shaddix** [comment]
yep, that's what I also ended up with. The only difference is that I wrap `actions.setOptions` in `useEffect` to prevent side effects in render function
```
useEffect(()=>{
  actions.setOptions((options) => (options.enabled = false));
}, []);
```

**Comment by MarkLyck** [comment]
@prevwong any chance we can get this fixed?

This is still broken in `"@craftjs/core": "0.2.0-beta.3"` :(

**Comment by prevwong** [comment]
Released in v0.2.0-beta.4 🎉

**Comment by MarkLyck** [comment]
@prevwong Thank you!

**Comment by prevwong** [comment]
Sorry folks, there seems to have been issue with @craftjs/utils when it was published to NPM as the version on NPM did not include the fix. 

Please update to 0.2.0-beta.5 to get the bug fix. Sorry for the inconvenience caused, will look into ways to prevent this from happening in the future releases!
