### ISSUE TITLE
I can't show data via data attribute

### ISSUE THREAD

**Issue by EdKo2001** [prevwong/craft.js#378]
```
import { Editor, Frame, Element } from "@craftjs/core";
import { Container } from "../components/selectors";
import { NextPageContext } from "next";

const Page = (props) => {
  return (
    <div>
      <h2>My App!</h2>
      <Editor
        resolver={{
          Container,
        }}
      >
        <h2>My Page Editor</h2>
        <Frame data={props?.formattedData}>
          {/* <Frame> */}
          <Element is={Container} canvas>
            // defines the Root Node
            <h2>Drag me around</h2>
            <Element is="div" style={{ background: "#333" }}>
              <p>Same here</p>
            </Element>
          </Element>
        </Frame>
      </Editor>
    </div>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const data = await import("../data/example.json");
  const formattedData = JSON.stringify(data);

  // Pass data to the page via props
  return { props: { formattedData } };
}

export default Page;
```

The error:
![image](https://user-images.githubusercontent.com/53624093/155005308-b0b45407-0f31-465a-af06-215317667ff9.png)

P.S. I've tried as JSON file from crast.js example and from saving my examples.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | 0.2.0-beta.2
| React            | 17.0.2
| TypeScript       | 3.7.5
| Browser          |
| npm/Yarn         | 8.3.0
| Operating System | Win 10

**Comment by EdKo2001** [comment]
any news so far?

**Comment by EdKo2001** [comment]
Sure, I'll do it shorty and send it here.
Thank you for your response.

**Comment by EdKo2001** [comment]
@ankri hello, I couldn't reproduce in the codesandbox just run into other issues, so just pushed to github.
Here we go: https://github.com/EdKo2001/craft
Then you visit that link - http://localhost:3001/page and find the described issue.
Thank you in advance.

**Comment by ankri** [comment]
Hey @EdKo2001 - I found your problem. It's the way you import the json. I created a [codesandbox](https://codesandbox.io/s/loving-snow-uqjlur?file=/pages/page.tsx) for you.

The problem is by importing the json via `import`: `const data = await import("../data/example2.json");` they also add a `default` attribute.

You can fix it by changing this line:

```diff
  const data = await import("../data/example.json");
-  const formattedData = JSON.stringify(data);
+  const formattedData = JSON.stringify(data.default);
```

**Comment by EdKo2001** [comment]
Wow, thank you a lot man!
