### ISSUE TITLE
Deserialize does not honor the hidden attribute

### ISSUE THREAD

**Issue by jmschneider** [prevwong/craft.js#38]
**Describe the bug**
`actions.deserialize` does not honor the `hidden` attribute on nodes.

**To Reproduce**
1. Hide a node
2. Serialize the current state with something like `state = query.serialize()`
3. Deserialize the state with `actions.deserialize(state)`
4. Your hidden node will reappear

**Expected behavior**
If the hidden attribute is set in the serialized state, the node should be created in a hidden state.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js           | 0.1.0-beta.1 |
| React            | 16.12.0 |
| TypeScript       | 3.7.5 |
| Browser          | Firefox 74.0b4 |
| npm/Yarn         | Yarn 1.22.0 |
| Operating System | OS X 10.15.3 |

**Comment by prevwong** [comment]
@jmschneider Good catch, thanks! 💯
