### ISSUE TITLE
Can't we use any eventlister like `onClick` on `<Element/>` tag that craftjs provide ???

### ISSUE THREAD

**Issue by ProPhycient5** [prevwong/craft.js#380]
**Is your feature request related to a problem? Please describe.**
Actually, I  need use a function on ```onClick``` event listener as attribute on ```<Element/>``` tag that craftjs provides. But that function is not invoked. How will I able to achieve that ????

**Describe the solution you'd like**
All the javascript/reactjs event listener must work on ```<Element/>``` tag.

**Additional context**

**Comment by prevwong** [comment]
When you use `<Element />`, you're creating a new Craft Node. You can only use literal values as props in a Craft Node since we can only serialise literal values and there's no way for us to store a function in the serialised Node object.

**Comment by ProPhycient5** [comment]
Okay got it @prevwong  but then if in use case, we need to add event Listener, then how can we achieve that ?

**Comment by prevwong** [comment]
You will need to create some kind of event handling system yourself. Instead of storing functions as props (which is not possible in Craft), you can store a simpler representation as a prop:
```tsx
type Event = {
   type: 'click' | 'mouseover';
   payload: {...}
}

type SomeElementProps = {
   events: Event[];
}

const SomeElement = (props: SomeElementProps) => {
    if ( props.event ) {
        // handle each props.event (eg: if event.type === "click", add an onClick Event Handler)
    }
}
```

**Comment by ProPhycient5** [comment]
Thanks for the idea. Here, I think it is mandatory to use `TypeScript`. I am not much handy with `TypeScript`, but I will keep your idea while implementing this type logic.

**Comment by prevwong** [comment]
Not really, TS is not mandatory. I'm just using TS here to make my point a bit clearer.

**Comment by ProPhycient5** [comment]
Then, it's fine.

**Comment by fizefeko** [comment]
> You will need to create some kind of event handling system yourself. Instead of storing functions as props (which is not possible in Craft), you can store a simpler representation as a prop:
> 
> ```tsx
> type Event = {
>    type: 'click' | 'mouseover';
>    payload: {...}
> }
> 
> type SomeElementProps = {
>    events: Event[];
> }
> 
> const SomeElement = (props: SomeElementProps) => {
>     if ( props.event ) {
>         // handle each props.event (eg: if event.type === "click", add an onClick Event Handler)
>     }
> }
> ```

Does this mean that we can't use useState hook and therefore we can't use hooks like useFormik for form management? We will be handling events just like we did before React.js was introduced(e.g in vanilla js or jquery).
I'm struggling with this issue and i wanna know if there is a way to deal with it
