### ISSUE TITLE
Item component so we can format the layers

### ISSUE THREAD

**Issue by bostondevin** [prevwong/craft.js#390]
LOVE LOVE LOVE LOVE YOU!!!!

We'll need an item formatter for the layers so we can modify what they look like...

Take whatever slotted html of the Layers Component is as an optional formatter?

**Comment by prevwong** [comment]
There's a `renderLayer` prop on the `<Layers />` component that allows you to render a custom layer item. 

By default, it renders the included `<DefaultLayer />` component (see [here](https://github.com/prevwong/craft.js/blob/develop/packages/layers/src/manager/LayerManagerProvider.tsx#L23))

You can refer to the [DefaultLayer](https://github.com/prevwong/craft.js/blob/develop/packages/layers/src/layers/DefaultLayer/DefaultLayer.tsx) component for reference on how to custom render a Layer item.
