### ISSUE TITLE
How is `setProp` of `actions` object different from `setProp` of `actions.history.ignore()` in  `useEditor` hook ?

### ISSUE THREAD

**Issue by ProPhycient5** [prevwong/craft.js#397]
For setting any new prop to a node/component, we use use `actions.setProp` method. From documentation, there is no proper mention of this `setProp` method of `actions.history.ignore()`, which I found on VScode editor hover.

```
(property) ignore: () => Delete<Delete<{
    setProp: (id: string, cb: (props: any) => void) => void;
    addLinkedNodeFromTree: (tree: NodeTree, parentId: string, id: string) => void;
    setNodeEvent: (eventType: NodeEventTypes, id: string) => void;
    ... 14 more ...;
    setHidden: (id: string, bool: boolean) => void;
}, "setNodeEvent" | ... 4 more ... | "setIndicator">, PrivateActions>
```

Please let me know the basic difference of `setProp` in these two cases. What should be the main purpose of `actions.history.ignore().setProp`  ?

**Comment by prevwong** [comment]
It is documented -> https://craft.js.org/docs/api/useEditor

`ignore() => ActionMethods; Run an action without recording its changes in the history`

`actions.setProp` will have its resulting changes being recorded in history whereas `actions.history.ignore().setProp` won't.

**Comment by ProPhycient5** [comment]
> It is documented -> https://craft.js.org/docs/api/useEditor
> 
> `ignore() => ActionMethods; Run an action without recording its changes in the history`
> 
> `actions.setProp` will have its resulting changes being recorded in history whereas `actions.history.ignore().setProp` won't.

**Comment by ProPhycient5** [comment]
Thank for the response. 
What is the benefit of not recording any changes to the history ?
I mean what is the use case, where we need something not to record within its history.

**Comment by ankri** [comment]
I answered that in your other [issue](https://github.com/prevwong/craft.js/issues/394#issuecomment-1070534832)
