### ISSUE TITLE
Render in Vue

### ISSUE THREAD

**Issue by iamtekeste** [prevwong/craft.js#403]
Has anyone tried reading the serialized json and rendering it in Vue or some other framework? I am allowed to use React to build the page builder but I don't have the freedom to use react when rendering the created page. I have a react and vue version of the user components
Is it possible to take the serialized json and render in Vue?

**Comment by slaat** [comment]
https://github.com/yoychen/v-craft

this might be of interest to you. Not sure how well this is maintained but there are craft.js alternatives for vue.

If you don't want to use something like this, you "just" need to write your own custom components in vue and render the json accordingly, I don't see why that should be an issue. It just might be a lot of manual work to achieve this though.

**Comment by iamtekeste** [comment]
> you "just" need to write your own custom components in vue and render the json accordingly

I will probably go with this route, I am curious to know how people went about parsing the json and rendering it? Probably have to write a function that does a depth first traversal and return the components
