### ISSUE TITLE
Can anyone make me understand how `create` method of `connectors` object works ?

### ISSUE THREAD

**Issue by ProPhycient5** [prevwong/craft.js#414]
Because, whenever the `Toolbox.tsx` code is rendered, this `create(dom, userElement)` is invoked, but I need to understand how it get converted to node when we do drag n drop on the canvas.

If I have serializedNode of a nodetree, how can I create actual node/component upon drag n drop way ?

**Comment by prevwong** [comment]
https://github.com/prevwong/craft.js/blob/develop/packages/core/src/events/DefaultEventHandlers.ts#L264

You can pass a callback function that returns a NodeTree as the 2nd argument in the `create` connector.
