### ISSUE TITLE
What is the main motivation to replace `string` datatype to `set` datatype of `state.events.selected` of `useEditor` hook ?

### ISSUE THREAD

**Issue by ProPhycient5** [prevwong/craft.js#418]
Like here, active is `set`, my question is - why is it required to make it `set` datatype ?
 Because what I could see that within `active`, it has one value i.e. id.
 
 
 
 
 ```const { active, related, selectedNodeObj } = useEditor((state) => ({active: state.events.selected, }));
```

**Comment by ankri** [comment]
Multiple selection of several components.

**Comment by ProPhycient5** [comment]
okay thanks for the information.
