### ISSUE TITLE
Ability to save json on edit

### ISSUE THREAD

**Issue by chungchi300** [prevwong/craft.js#45]
**Is your feature request related to a problem? Please describe.**
I want to save the json to the database when the canvas is changed for loading the page in the future. Right now the only way to do it is requesting the user to manual press the button
```
  <MaterialButton
            className="copy-state-btn"
            size="small"
            variant="outlined"
            color="secondary"
            onClick={() => {
              const json = query.serialize();
            //sent the json the server
              setSnackbarMessage("Saved");
            }}
            style={{ marginRight: "10px" }}
          >
           Save
          </MaterialButton>
```

**Describe the solution you'd like**
Solution 1
```
   <Frame json={JSON.stringify(value)} onChange={query=>{}} >
```

```
 const { actions, query, enabled } = useEditor(state => ({
    enabled: state.options.enabled
  }));
query.onChange().

```

Again, what a great library there!

**Comment by prevwong** [comment]
I believe this can be achieved via performing side effects on the collected state information from `useEditor`. 

For example, we can query for the serialised json within the collector function and perform a side effect to save the json whenever it changes:

```jsx
const SaveOnEdit = () => {
  const {query, json} = useEditor((state, query)=> ({
     json: query.serialize()
  });
  
  // Call whenever json changes
  useEffect(() => {
     // Save to server
  }, [json]);

 return null;
}

const App = () => {
   return (
     <Editor resolvers={...}>
         <SaveOnEdit />
         <Frame>...</Frame>
     </Editor>
  )
}
```

**Comment by prevwong** [comment]
This feature has been added in! 

```jsx
<Editor onNodesChange={query => {
   const json = query.serialize();
   ...
} />

**Comment by johann-taberlet** [comment]
This callback doesn't appear to be triggered when a user modifies component properties, such as margins and paddings, through the settings panel. 
Am I making a mistake, or is this the intended behavior? 
If so, how can I ensure that the most recent node states, including updated properties, are persisted while editing?

**Comment by asish-tailwind** [comment]
> This callback doesn't appear to be triggered when a user modifies component properties, such as margins and paddings, through the settings panel. Am I making a mistake, or is this the intended behavior? If so, how can I ensure that the most recent node states, including updated properties, are persisted while editing?

Is it working now ?
