### ISSUE TITLE
Connectors will not work when the Editor is initially disabled 

### ISSUE THREAD

**Issue by prevwong** [prevwong/craft.js#46]
**Describe the bug**

When the `enabled` prop in `<Editor />` is initially set to false, all connectors fail to work even after the prop is set to true.

```jsx
const App = () => {
   const [enabled, setEnabled] = useState(false);

   return (
      <Editor enabled={enabled}
         ....
      </Editor>
   )
}

const Btn = () => {
    const { connectors } = useNode();
     // connectors wont work even after the Editor is enabled
    return <button ref={connectors.connect}>Click</button>
}
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js           | v0.1.0-beta-3

**Comment by bladepop** [comment]
We've also experienced this, our work around was to completely re-render the editor when changing the enabled/disabled
