### ISSUE TITLE
Is dynamically updating the resolver possible?

### ISSUE THREAD

**Issue by LiveDuo** [prevwong/craft.js#467]
The use case is having different themes and each having quite a few components.

To prevent overloading the browser, can I update the resolver components on the fly when the user changes theme?

**Comment by LiveDuo** [comment]
My bad. Works by updating the `resolver` variable in the editor.

**Comment by thirstycode** [comment]
Hello @LiveDuo , How do you handle the rendering of nonavailable resolvers? I'm facing an issue where I have multiple versions of my app with different sets of resolvers. If I load the saved state in another version, it stops working (Resolver not found error).

**Comment by LiveDuo** [comment]
We ended up doing something quite complex. Our components are stored in a single component that handles most HTML elements [Child.tsx](https://github.com/LiveDuo/destack/blob/feature/craftjs/lib/destack/src/themes/shared/Child.tsx).

For your case might be best to reload the editor with a new set of resolvers. That means that along with your saved state you'd have to save which version it is so you know when you are loading it.

**Comment by AstralBaby** [comment]
May i ask how do you reset the editor resolvers?

**Comment by LiveDuo** [comment]
@AstralBaby Just loading the resolver through react context https://github.com/LiveDuo/destack/blob/87e01f444526a774606abc4231c9953923e59e10/lib/client/craft/editor/Editor.tsx#L71. It's been a while since I built a custom editor for https://github.com/LiveDuo/destack and I don't remember the exacts.
