### ISSUE TITLE
Nested nodes are duplicated

### ISSUE THREAD

**Issue by tsaunde123** [prevwong/craft.js#473]
**Describe the bug**
When nesting nodes in the `<Frame>` the nested nodes appear to be duplicated.

**To Reproduce**

1. Define nested divs in the editor frame. For example:

```
<Editor resolver={UserComponents}>
      <Topbar />
      <Frame>
         <div>
           <div>Nested Child</div>
         </div>
      </Frame>
</Editor>
```

Note: the Topbar component has a button to print/export the nodes state, similar to how the CraftJS basic tutorial implements the topbar.

2. Save the state and print/export the nodes e.g.:

```
const nodes = query.getSerializedNodes();
console.log(json);
```

3. See the below output:

```
{
  "ROOT": {
    "type": "div",
    "isCanvas": false,
    "props": {},
    "displayName": "div",
    "custom": {},
    "hidden": false,
    "nodes": [
      "aVOIFbx8jQ"
    ],
    "linkedNodes": {}
  },
  "tDjSso8YcN": {
    "type": "div",
    "isCanvas": false,
    "props": {
      "children": "Nested Child"
    },
    "displayName": "div",
    "custom": {},
    "parent": "ROOT",
    "hidden": false,
    "nodes": [],
    "linkedNodes": {}
  },
  "aVOIFbx8jQ": {
    "type": "div",
    "isCanvas": false,
    "props": {
      "children": "Nested Child"
    },
    "displayName": "div",
    "custom": {},
    "parent": "ROOT",
    "hidden": false,
    "nodes": [],
    "linkedNodes": {}
  }
}
```

As you can see in the output above, the `ROOT` node appears to have a single child node `aVOIFbx8jQ` however there are two nodes `aVOIFbx8jQ` and `tDjSso8YcN` pointing to the `ROOT` node as a parent.

**Expected behavior**
The root node should have a single child `aVOIFbx8jQ` and so there should only be two nodes: `ROOT` and `aVOIFbx8jQ`.

**Screenshots**
N/A

**Additional context**

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | `0.2.0-beta.8`
| React            | `18.2.0`
| TypeScript       | `^4.8.4`
| Browser          | `Chrome Version 107.0.5304.110 (Official Build) (arm64)`
| npm/Yarn         | `npm 8.19.1`
| Operating System | `macOS Monterey 12.3`

**Comment by martin-dimi** [comment]
+1 We are experiencing the same issue. We have to remove the dups manually. Are we doing something wrong?

**Comment by khangt1k25** [comment]
+1 I am facing this bug too. How can we remove that?

**Comment by ziyingjing** [comment]
+1 React 18 reactStrictMode: true Can cause this problem
