### ISSUE TITLE
Implement with Nextjs not working

### ISSUE THREAD

**Issue by ilomon10** [prevwong/craft.js#476]
I love that i can discover this library. It fits with my current project.
Im working with next on that project, but when i tried to implement this library, it didn't working. Tried the tutorial on docs but didnt get luck.

There is no error on screen.
When i inspect the element it doesn't applied any attributes on that element.

My current state is, 
https://craft.js.org/docs/guides/basic-tutorial/#defining-droppable-regions
I didnt install/use material-ui, just use vanilla element.

By the way i use next version 12

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | 0.2 beta
| React            | 17
| Next | 12
| Browser          | Chrome Latest
| npm/Yarn         | Latest
| Operating System | WSL Win 10

**Comment by ilomon10** [comment]
Now its working

**Comment by fpoirier1** [comment]
@ilomon10 Do you remember what you did to make it work ?

**Comment by ilomon10** [comment]
@fpoirier1 Do you have the same experience? or can you share your project setup, so i can help you to solve it.
