### ISSUE TITLE
Did you stop updating?

### ISSUE THREAD

**Issue by LengYXin** [prevwong/craft.js#487]
Did you stop updating？？？？

**Comment by prevwong** [comment]
Check out the update here: https://github.com/prevwong/craft.js/issues/507

This will include some exciting new features to Craft, including realtime collaboration in the near future!

**Comment by aansarileap** [comment]
Hi @prevwong,

I came across your last update on issue [507](https://github.com/prevwong/craft.js/issues/507) from April 4th, 2023, and noticed that there hasn’t been a new release or major update to Craft.js in about a year.

I’m currently evaluating Craft.js for use in a production project and wanted to understand your thoughts on the current state of the library and its future direction.

My main concern is long-term stability and compatibility, especially with upcoming React upgrades. I want to avoid dependency issues or breaking changes if React versions evolve.

Could you please share:

Whether Craft.js is still actively maintained or planned to be maintained?

If it is safe to use Craft.js in production today?

Your thoughts on React version compatibility going forward?

I really appreciate the work you’ve put into Craft.js — it’s a great project and fits our use case very well. I just want to make sure it’s a safe long-term choice before committing to it.

Thanks in advance for your time and guidance.

Best regards,
Abdulla

**Comment by magnus-trent** [comment]
@aansarileap you are 10x better off forking and finishing it with the help of Claude Code or something.
