### ISSUE TITLE
Add Blocks via Button Click (Not Drag)

### ISSUE THREAD

**Issue by ITCuw** [prevwong/craft.js#498]
**Is your feature request related to a problem? Please describe.**
It's frustrating that the only way to add content is via drag. Especially when I want to generate content for a user and have to resort to manipulating the serialized JSON object which gets buggy fast.

**Describe the solution you'd like**
I want users to be able to fill out a form and then once they click a button it generates a new element with their content inside it and adds the element within a specific container.

**Additional context**
Here is a sandbox where I tried getting it to work, however it seems id values within the `<Editor>` are not captured.
https://codesandbox.io/s/craft-js-add-block-with-button-iq05ux?file=/src/components/AddNewBlockButton.js

**Comment by msahajwani** [comment]
Have you had any success with this? I'm looking to do something similar. Specifically, I'm wondering where in the node tree we should be instructing the button to add the block and how.

**Comment by ITCuw** [comment]
@msahajwani I have not found a simple solution but I will keep you posted.

**Comment by ITCuw** [comment]
@msahajwani  Have you read this part of the documentation on creating nodes: [Creating new nodes](https://craft.js.org/docs/api/useEditor#creating-new-nodes)? 

You can use
```
const nodeTree = query.parseReactElement(<h2>Hi</h2>).toNodeTree();
        actions.addNodeTree(nodeTree);
```

 to create a new node and then you can use  `actions.move()` to move the item into the correct parent component: [Moving nodes](https://craft.js.org/docs/api/useEditor#moving-a-node)

**Comment by thirstycode** [comment]
You can attach an onClick listener and then use

```
const nodeID = getRandomId();
const freshNode = {
      id: nodeID,
      data: {
        type: Renderer,
        props: {},
      },
};
const nodeToAdd = query.parseFreshNode(freshNode).toNode();
actions.add(nodeToAdd, ROOT_NODE);
```

**Comment by ITCuw** [comment]
Thank you @thirstycode
