### ISSUE TITLE
Is there a way to clear the selected state?

### ISSUE THREAD

**Issue by eric-mathison** [prevwong/craft.js#500]
The goal here is to only show the settings panel while a user component is selected and close when nothing is selected. Is there a supported way of doing this?

**Comment by ITCuw** [comment]
Hi Eric,
```
const { actions } = useEditor();
actions. selectNode(null);
```
This will deselect nodes by setting the selected node value to empty.

**Comment by eric-mathison** [comment]
> This will deselect nodes by setting the selected node value to empty.

Thanks.
