### ISSUE TITLE
Enabled prop is required since last release

### ISSUE THREAD

**Issue by ismajl-ramadani** [prevwong/craft.js#508]
If you updated to the latest version of craft, you might see that the editor is disabled. Thats because the prop "enabled" of Editor is required now. You have to explicitly tell the editor that you want to enable it. 

I'm not sure if this is by design, but this https://github.com/prevwong/craft.js/commit/c74f4c94e1722c4f515a34ebf8718af896661de7 
affected it.

@prevwong lmk if this is intentionally so I can update the docs, or if its an issue  so I can see and fix this.

**Comment by prevwong** [comment]
Not intentional  🥲 Opened a PR for the fix!

**Comment by ismajl-ramadani** [comment]
Testing it now will let you know if that should've fixed it.
