### ISSUE TITLE
How do you import DefaultLayerHeader from the layers package?

### ISSUE THREAD

**Issue by jorgegonzalez** [prevwong/craft.js#512]
I keep getting typescript issues trying to import this particular component to try and custom some elements of the Layers component.

**Comment by ismajl-ramadani** [comment]
Can you share the issues please?

**Comment by jorgegonzalez** [comment]
@ismajl-ramadani I was trying `import { DefaultLayerHeader } from '@craftjs/layers';` and received `TS2305: Module '"@craftjs/layers"' has no exported member 'DefaultLayerHeader'.`

**Comment by ismajl-ramadani** [comment]
It should be fine after the merge. It seems that DefaultLayerHeader is not exported from the layers package at all. Will confirm this with @prevwong.

**Comment by jorgegonzalez** [comment]
Yeah looks like it @ismajl-ramadani  :open_mouth:

**Comment by jorgegonzalez** [comment]
Fixed in #433
