### ISSUE TITLE
Documentation search is broken

### ISSUE THREAD

**Issue by ismajl-ramadani** [prevwong/craft.js#513]
When trying to search for content on the landing page of craft, It shows "No results for..." for any keyword.

**Comment by ismajl-ramadani** [comment]
@prevwong  can you take a look at this whenever you have some time

**Comment by ismajl-ramadani** [comment]
It looks like Algolia is returning empty results for any query.

**Comment by prevwong** [comment]
Yeah I will contact Algolia. The indexes in the dashboard have the correct results, but for some reason it doesn't appear in the UI

**Comment by prevwong** [comment]
Fixed in [84adfd1](https://github.com/prevwong/craft.js/commit/84adfd164d968cd556f6bd9b09e76dcda1274021)
