### ISSUE TITLE
onNodeChange should provide a reference/id of the node changed

### ISSUE THREAD

**Issue by yanhernt** [prevwong/craft.js#528]
**Is your feature request related to a problem? Please describe.**
I am just wondering if there is anyway to know which node changed from the onNodesChange event handler as currently from the docs, I can only get the editor query from the event.

**Describe the solution you'd like**
onNodesChange should provide a reference or id of the node that changed such that 
`onNodesChange={node=>handleNodeChange(node)}`

**Comment by yanhernt** [comment]
Hi @ismajl-ramadani , thanks for the response but I've actually found a workaround for my solution. Will proceed to close this issue for now.

**Comment by jorgegonzalez** [comment]
It would actually be great to have this functionality. I would love to be able to write something like the snippet in the original post, @yanhernt I'm curious what your workaround was?
