### ISSUE TITLE
Editing the rules of nodes - may already be possible but I am not sure

### ISSUE THREAD

**Issue by ITCuw** [prevwong/craft.js#531]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I have to manually recreate a user's website because I have to update the rules of the node.

**Describe the solution you'd like**
It would be nice to create a way of using setProp but for setting the rules.

**Comment by ismajl-ramadani** [comment]
Hi @ITCuw, can you please elaborate on your question?  This seems to be an issue with how you're using the craft.js package rather than with the core functionality, correct? If that's the case can you please close the issue and ask the question on the Discussions tab or through the Discord server.

**Comment by ismajl-ramadani** [comment]
@ITCuw I'm closing this issue since it's not relevant with the core functionality of craft.js. Please open a discussion or use discord for these kind of questions.
