### ISSUE TITLE
Error canvas when initialize <Editor />

### ISSUE THREAD

**Issue by pedroota** [prevwong/craft.js#535]
**Describe the bug**
I'm creating an app with Craft.js and my canvas is not apearing on screen to drag n' drop. 

![image](https://github.com/prevwong/craft.js/assets/48136045/204c9045-20fb-4621-b49d-979a3be433a5)

If you see on the image, it's all done right. Exactly how it's on the docs. And yes, I imported all correctly.

![image](https://github.com/prevwong/craft.js/assets/48136045/d0e6bc85-58ba-4594-9a86-479ffe0c590e)

**Comment by hugominas** [comment]
Hi Pedro, in your editor props you are setting enabled to false try `enabled={true}`

**Comment by pedroota** [comment]
> Hi Pedro, in your editor props you are setting enabled to false try `enabled={true}`

As you can see below, I set "enabled" to true, but I'm still experiencing the same issue. Additionally, I included the <Toolbox /> component to render the draggable components on the view, and unfortunately, I'm encountering the same problem.

![image](https://github.com/prevwong/craft.js/assets/48136045/638db089-575c-431b-8626-5e8af6354471)

How the view looks like:

![image](https://github.com/prevwong/craft.js/assets/48136045/3ceb4a30-8e00-421a-9e61-31530da5e573)

**Comment by pedroota** [comment]
> Hi Pedro, in your editor props you are setting enabled to false try `enabled={true}`

I found the bug, the component that I'm rendering for each node (RenderNode) at onRender property was causing this error. Thank you for your reply!

**Comment by hristokoev** [comment]
Hi Pedro, I have the exact same issue. My RenderNode is literally this:

`import React from 'react';

const RenderNode = ({ node }) => {
	return (
		<>
			{node}
		</>
	)
}

export default RenderNode;`

I would like to encapsulate every element into a div and add some hover functionality, so I thought this will help. How did you fix it? Thanks!
