### ISSUE TITLE
Duplicating a node twice fails due to error in `actions.setNodeEvent`

### ISSUE THREAD

**Issue by mresposito** [prevwong/craft.js#57]
**Describe the bug**

When trying to duplicate a node twice in a row, it fails due to the following error:
```
react-dom.development.js?61bb:11102 Uncaught TypeError: Cannot read property 'events' of undefined
    at Object.setNodeEvent (index.js?d4d4:1)
    at eval (index.js?b31b:1)
    at Immer.produce (immer.module.js?57f8:792)
    at eval (index.js?b31b:1)
    at updateReducer (react-dom.development.js?61bb:15135)
    at Object.useReducer (react-dom.development.js?61bb:15932)
    at Object.useReducer (react.development.js?72d0:1501)
    at Object.useMethods (index.js?b31b:1)
    at useEditorStore (index.js?d4d4:1)
    at Editor (index.js?d4d4:1)
```

To duplicate, we use the following function:
```
  const { actions, nodes, selectedNodeId } = useEditor((editorState) => ({
       selectedNodeId: editorState.events.selected,
       nodes: editorState.nodes,
    }));

    const duplicateNode = (nodeIdToDuplicate: string) => {
      if (!selectedNodeId || !nodeIdToDuplicate || nodeIdToDuplicate === CRAFT_ROOT_ID) {
        return;
      }
      // we check that the node still exists here because it might have been deleted.
      const selectedNode = nodes[selectedNodeId];
      const parentId = selectedNode.data.parent || CRAFT_ROOT_ID;
      const nodeToCopy = { ...nodes[nodeIdToDuplicate], id: newId() };
      if (!nodeToCopy) {
        return;
      }
      actions.add(nodeToCopy, selectedNode.data.parent || CRAFT_ROOT_ID);
      actions.selectNode(nodeToCopy.id);
      // move the node to be right next to the current node.
      const newIndex = nodes[parentId].data.nodes.indexOf(selectedNodeId) + 1;
      actions.move(nodeToCopy.id, parentId, newIndex);
    },

```

**To Reproduce**

When duplicating a node using the above function, try to copy it twice in a row and it will throw an error

**Expected behavior**
it shouldn't throw an error

**Screenshots**
![captured](https://user-images.githubusercontent.com/1311832/78451571-34157600-767e-11ea-9894-033560a1a8fc.gif)

**Additional context**

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | beta.4
| React            | 16.13
| TypeScript       | yes
| Browser          | chrome 
| npm/Yarn         | yarn
| Operating System | osx high sierra

**Comment by mresposito** [comment]
Closing this issue as a refactor into the `delete` and `add` actions in our fork of Craft fixed it.

**Comment by jmschneider** [comment]
@mresposito are you able to share your fork or did you create a PR with the fix?

**Comment by mresposito** [comment]
You can check out our fork here: https://github.com/candulabs/craft.js

However, I would warn you against using this fork in production as it will not be stable and we'll be making breaking changes to it. 

We'll be opening some PRs to merge some of the fixes back to the main repo soon, so hold tight.

**Comment by jmschneider** [comment]
Awesome, I look forward to it. I've been having some issues with the `delete` action so I'm hoping your PRs may address the issue.
