### ISSUE TITLE
Importing a component from an external package will result in invariant failure

### ISSUE THREAD

**Issue by Traveller23** [prevwong/craft.js#580]
**Describe the bug**
I added an npm package to "examples/basic", and created a component in that package, which I then referenced in "examples/basic".

project: https://github.com/Traveller23/craftjs-sandbox
changes: https://github.com/Traveller23/craftjs-sandbox/commit/38fde0f973fb2a271e1861c2a52a7e152d80f8f8

This is what it looks like after starting the project:

![0](https://github.com/prevwong/craft.js/assets/117014547/29f7a96e-6ef3-4d9b-9ece-a80a82a0406d)

When I drag this "Test" component to the center, the page shows the following error:

![1](https://github.com/prevwong/craft.js/assets/117014547/44c0062f-1570-402b-9f95-23ace71f675c)
```
Error: Invariant failed: You can only use useNode in the context of <Editor />. 
Please only use useNode in components that are children of the <Editor /> component.
```

**Additional context**
Multiplayer collaborative projects can be greatly impacted by not being able to create components with additional packages.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | 0.2.2
| React            | 18.2.0
| TypeScript       | 5.2.2
| Browser          | Chrome 119
| npm/Yarn         | 9.8.1
| Operating System | Window 10

**Comment by Traveller23** [comment]
@prevwong Our company is currently using `craftjs` as the base tool for its low-code project, which has been underway for two months now.
We didn't realize this until we started splitting the project into smaller projects. This has thwarted our development plans.
Is it possible that I can fix this issue by modifying the source code directly?
I currently have absolutely no idea why this issue is occurring. Why does `useContext(NodeContext)` not work just because the source code of the component is in a different package?

**Comment by Traveller23** [comment]
Also, I would like to know how to solve this problem if the package is added in `package.json`.
The way we actually work together is to bring in other packages in the main project, rather than putting all the code into one project. I'm just doing this for the sake of the demo.

**Comment by Traveller23** [comment]
Finally I found the cause of the problem: https://stackoverflow.com/questions/58754732/how-to-consume-same-react-context-coming-from-different-packages
The core problem is that all packages must share a single `craftjs`.
It may not be enough to strictly specify the version of `craftjs`, but you need to make it so that library packages don't export code of `craftjs`. This is done in `vite` with "rollupOptions.external" configs.

**Comment by ajgianthead** [comment]
how did you fix it?

**Comment by Traveller23** [comment]
> how did you fix it?

Assuming that your package relies on craft.js, and that this package is relied on by other packages as a library, then you need to write this in this package's `vite.config.js`:

```javascript
import {resolve} from "path";
import {defineConfig} from "vite";

export default defineConfig({
    build: {
        lib: {
            entry: {
                "index": resolve(__dirname, "src/index.tsx"),
            },
            name: "my-library",
            formats: ["es"],
            fileName: "[name]",
        },
        rollupOptions: {
            input: {
                "index": "src/index.tsx",
            },
            external: [
                "react", "react-dom",
                /@craftjs\/core(\/.+)?/, /@craftjs\/utils(\/.+)?/,
            ],
        },
        sourcemap: true,
    },
});
```

**Comment by jdeitawimostafa** [comment]
i tried your solution , It didn't work with me !! 

I am scared that i missed something , can we schedule a quick meeting to discuss the solution together if you may ? i am stuck that's why i am asking for a meeting !

**Comment by rafark** [comment]
Having this problem too. The editor warps the main < App> but I get this error if i try to use useEditor in a component outside of < Frame>
