### ISSUE TITLE
Multiple frames inside of an editor

### ISSUE THREAD

**Issue by Chepush** [prevwong/craft.js#600]
Is it possible to have multiple `<Frame>` components inside of the `<Editor>`? 

I've tried to achieve something similar to what Framer has (screenshot attached) with multiple frames with different widths. However, the behavior breaks when I put multiple frames into one editor. Drag & Drop indicators are displayed only on the last frame. Also, the "node" returned from the useNode() hook is always the one from the last frame. Is there a workaround for such case?

![image](https://github.com/prevwong/craft.js/assets/47068825/7af5817a-dd7c-45f7-a5a7-b89ba074e659)

**Comment by prevwong** [comment]
Currently no, and it will take quite a bit of work to support this unfortunately

**Comment by 0x0wen** [comment]
> Currently no, and it will take quite a bit of work to support this unfortunately

Do you have any idea for the workaround? Just hints, that would be very helpful!
