### ISSUE TITLE
Nested elements are created as Linked Nodes instead of child nodes

### ISSUE THREAD

**Issue by caseymilne** [prevwong/craft.js#603]
**Describe the bug**
I don't know if this is a bug or normal behavior but when I provide a toolbox to drop in a component with multiple Elements nested, these do not show up as parent/child in the node tree data. This means in my custom layers I see only the top node. Upon inspection I find that top node has linked node, and those nodes are created properly, but they are not connected as children. Strangely though, in the UI they do appear nested, so maybe that relationship is maintained somewhere? Is this normal behavior? Because this is clearly a tree, I want them made as a tree rather than using linked nodes, which I thought would be the normal default behavior?

```
import React from 'react';
import { Element, useNode } from "@craftjs/core";
import StandardProperties from '../Properties/StandardProperties';
import { SectionElement } from '../UserComponents/SectionElement';
import { ImgElement } from '../UserComponents/ImgElement';

export const HeroTypeA = ({ classes }) => {

	const { connectors: { connect, drag } } = useNode();

	return (
		<Element id="hero-section" is={SectionElement} ref={ref => connect(drag(ref))} classes={classes} canvas>
			<Element id="hero-logo" is={ImgElement} ref={ref => connect(drag(ref))} classes={classes} src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"/>
		</Element>
  );

}

HeroTypeA.craft = {
	displayName: "Hero Type A",
	props: {
		classes: '',
	},
	related: {
    settings: StandardProperties,
  },
	isCanvas: true,
}
```

**Comment by caseymilne** [comment]
I realized after creating more nested Elements that the children further nested are stored in data.nodes[]. It's just this component itself where it is parented to ROOT or whatever parent it's dropped into, and it uses data.linkedNodes instead of data.nodes[] to store the reference to it's first child.

**Comment by levietdat** [comment]
Do you have a way to fix them? Could you please share it with me? @caseymilne
