### ISSUE TITLE
Looks very much likes grapesjs

### ISSUE THREAD

**Issue by allyraza** [prevwong/craft.js#61]
This looks like grapesjs what is the motivation behind the project, it looks interesting though

**Comment by prevwong** [comment]
Grape.js provides a page editor whereas Craft.js provides an abstraction for developers to build their own unique page editor however they want it to be. The only similarity between the two is the drag-n-drop logic used in Craft.js, which is based on Grape.js. 

This is described pretty clearly on the README. Please have a look next time before creating an issue. Alternatively, use the Discord server to ask questions like this.

**Comment by allyraza** [comment]
you can create custom page editor with `grapes.js` as well, I don't see much difference other than react layer you have bolted. 

Also there is no need to be rude I read you mentioned grapes.js in the acknowledgement section, what is different compared to `grapes.js`
