### ISSUE TITLE
Undefined error when selecting object then deleting.

### ISSUE THREAD

**Issue by tonychan96** [prevwong/craft.js#62]
**Describe the bug**
`Cannot read property 'data' of undefined
    at Object.setCustom`

**To Reproduce**
This can be replicated at https://craft.js.org/.  Select a text element then press the delete trash can. 

This error only occurs when you explicitly select the object.  Hovering over the object then pressing delete will still work.

This error seems to only happen to child components, you can successfully delete the outer most parent after clicking it, but not its inner components

**Expected behavior**
Select object -> press delete -> object deletes

![image](https://user-images.githubusercontent.com/22465526/79492056-4a9fc380-7fd4-11ea-90e0-8817e949c917.png)

**Comment by linxianxi** [comment]
@prevwong  still happen in beta.20.https://craft.js.org/

**Comment by hugominas** [comment]
Same is happening to me but only on some elements. I am using version 0.2.0-alpha.26

I guess t is not defined for some reason I wonder if if something wrong with my components 
`...t.data.linkedNodes&&Object.values(t.data.linkedNodes).map((function(e){return o(e)}...`

![Screenshot from 2021-08-31 15-46-32](https://user-images.githubusercontent.com/3314986/131524527-635bcda5-0830-4494-9f0b-766289a6066d.png)

**Comment by hugominas** [comment]
I consoled log the node data before deleting, and I got the all node data so this should be defined.

`query.node(settings.id),
 query.node(settings.id).get()`

![Screenshot from 2021-08-31 16-13-48](https://user-images.githubusercontent.com/3314986/131529223-2d12c673-2886-4dc7-af66-106dc1a16c2b.png)

**Comment by IvaKop** [comment]
I'm having the exact same issue. Unless we are missing something obvious, perhaps this issue should be reopened?

**Comment by geohuz** [comment]
I'm having the same issue, do we have a solution now?

**Comment by geohuz** [comment]
Here is my page on codesandbox, select the container from layers manager and delete it, then the errors appear.
https://codesandbox.io/s/practical-lucy-j8050f?file=/src/App.js
