### ISSUE TITLE
Avoid animation of the element snapping back to its origin position when element is dropped.

### ISSUE THREAD

**Issue by fpoirier1** [prevwong/craft.js#620]
First and for most, this library is a state of the art, thank you very much! 

**Describe the bug**
When dropping an element, there is an animation of the element snapping back to its origin position before the change happens.

**To Reproduce**

1. Go to demo example (https://craft.js.org/examples/basic)
2. Drag the 'Click me' button far to the bottom of the page
3. You see the placeholder going back to is original position before being moved under the 'It's me again!' block.

**Expected behavior**
We would expect the change to happens instantaneously.

**Screenshots**
https://github.com/prevwong/craft.js/assets/1587658/33bdea05-96a5-4902-9662-b634f8bb2409

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         |  0.2.5
| React            | 18.2.0
| TypeScript       | 
| Browser          | Chrome
| npm/Yarn         |
| Operating System | Mac OSX

**Comment by prevwong** [comment]
Fixed in #634!
