### ISSUE TITLE
Selected node is reset when i interact with editor on production

### ISSUE THREAD

**Issue by majdnaji** [prevwong/craft.js#647]
**Describe the bug**
when i do any interaction with the editor either manually using drag and drop or through useNode().action.setProp the selected node is reset this is only happening on production.
im using the react app inside an iframe

**To Reproduce**

1. use setProp
2. deploy on a production server inside an iframe
3. when setProp is executed the selected node stops being selected

**Expected behavior**
the selected node should still be selected adter setProp is used

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | 0.2.4
| Nextjs            | 14.1.0
| TypeScript       | 5
| Browser          | google chrome
| npm/Yarn         | npm 10.2.4

**Comment by majdnaji** [comment]
it was resolved. the issue isn't related to craftjs.

**Comment by MarkLyck** [comment]
@majdnaji Could you share what the problem was?
