### ISSUE TITLE
intercepting dropped elements

### ISSUE THREAD

**Issue by majdnaji** [prevwong/craft.js#665]
**Is your feature request related to a problem? Please describe.**
i'm trying to to find a way to display a message when the user tries to drop an element into an area where the element being dropped is not allowed, i tried this using the component's rule functions but it's firing for all components the dragged element is passing over instead of happening only once for  the component the drop happens in

**Comment by jjoderis** [comment]
You could do something like this:

```
class CustomEventHandlers extends DefaultEventHandlers {
  handlers() {
    const defaultHandlers = super.handlers();

    const { query } = this.options.store;

    return {
      ...defaultHandlers,
      drag: (el: HTMLElement, id: string) => {
        const unbindDrop = this.addCraftEventListener(el, "dragend", (e) => {
          e.craft.stopPropagation();

          if (!this.dragTarget || this.dragTarget.type === "new") return;

          const target = this.positioner?.getIndicator().placement.parent;
          const nodes = this.dragTarget.nodes.map((id) => query.node(id).get());

          if (target) {
            for (const node of nodes) {
              // check if the element can be dropped
              if (!node.rules.canDrop(target, node, query.node)) {
                // do something if not
                alert("Can't drop here!");
              }
            }
          }
        });

        const unbindDefault = defaultHandlers.drag(el, id);

        return () => {
          unbindDefault();
          unbindDrop();
        };
      },
      create: (
        el: HTMLElement,
        userElement: React.ReactElement | (() => NodeTree | React.ReactElement)
      ) => {
        const unbindDrop = this.addCraftEventListener(el, "dragend", (e) => {
          e.craft.stopPropagation();

          if (!this.dragTarget || this.dragTarget.type === "existing") return;

          const target = this.positioner?.getIndicator().placement.parent;

          const nodeIds = Object.keys(this.dragTarget.tree.nodes);
          const nodes = nodeIds.map((id) => this.dragTarget.tree.nodes[id]);

          if (target) {
            for (const node of nodes) {
              // check if the element can be dropped
              if (!node.rules.canDrop(target, node, query.node)) {
                // do something if not
                alert("Can't drop here!");
              }
            }
          }
        });

        const unbindDefault = defaultHandlers.create(el, userElement);

        return () => {
          unbindDefault();
          unbindDrop();
        };
      },
    };
  }
}

...

<Editor
  ...
  handlers={(store) =>
    new CustomEventHandlers({
      store,
      isMultiSelectEnabled: () => false,
      removeHoverOnMouseleave: true,
    })
  }
>

...
```

**Comment by majdnaji** [comment]
> You could do something like this:
> 
> ```
> class CustomEventHandlers extends DefaultEventHandlers {
>   handlers() {
>     const defaultHandlers = super.handlers();
> 
>     const { query } = this.options.store;
> 
>     return {
>       ...defaultHandlers,
>       drag: (el: HTMLElement, id: string) => {
>         const unbindDrop = this.addCraftEventListener(el, "dragend", (e) => {
>           e.craft.stopPropagation();
> 
>           if (!this.dragTarget || this.dragTarget.type === "new") return;
> 
>           const target = this.positioner?.getIndicator().placement.parent;
>           const nodes = this.dragTarget.nodes.map((id) => query.node(id).get());
> 
>           if (target) {
>             for (const node of nodes) {
>               // check if the element can be dropped
>               if (!node.rules.canDrop(target, node, query.node)) {
>                 // do something if not
>                 alert("Can't drop here!");
>               }
>             }
>           }
>         });
> 
>         const unbindDefault = defaultHandlers.drag(el, id);
> 
>         return () => {
>           unbindDefault();
>           unbindDrop();
>         };
>       },
>       create: (
>         el: HTMLElement,
>         userElement: React.ReactElement | (() => NodeTree | React.ReactElement)
>       ) => {
>         const unbindDrop = this.addCraftEventListener(el, "dragend", (e) => {
>           e.craft.stopPropagation();
> 
>           if (!this.dragTarget || this.dragTarget.type === "existing") return;
> 
>           const target = this.positioner?.getIndicator().placement.parent;
> 
>           const nodeIds = Object.keys(this.dragTarget.tree.nodes);
>           const nodes = nodeIds.map((id) => this.dragTarget.tree.nodes[id]);
> 
>           if (target) {
>             for (const node of nodes) {
>               // check if the element can be dropped
>               if (!node.rules.canDrop(target, node, query.node)) {
>                 // do something if not
>                 alert("Can't drop here!");
>               }
>             }
>           }
>         });
> 
>         const unbindDefault = defaultHandlers.create(el, userElement);
> 
>         return () => {
>           unbindDefault();
>           unbindDrop();
>         };
>       },
>     };
>   }
> }
> 
> ...
> 
> <Editor
>   ...
>   handlers={(store) =>
>     new CustomEventHandlers({
>       store,
>       isMultiSelectEnabled: () => false,
>       removeHoverOnMouseleave: true,
>     })
>   }
> >
> 
> ...
> ```

thank you, this solved my case
