### ISSUE TITLE
Initialising a new Editor, Frame and Canvas with some children results in an empty canvas

### ISSUE THREAD

**Issue by riccardocaranfil** [prevwong/craft.js#68]
I use the basic tutorial guide available at this link
[https://craft.js.org/r/docs/guides/basic-tutorial#overview](https://craft.js.org/r/docs/guides/basic-tutorial#overview)

I just create a text component to try out the library and when I run initially my Canvas is empty even if I entered in some TextComponents

**Screenshots**

The result

![Schermata 2020-04-26 alle 22 39 44](https://user-images.githubusercontent.com/13602797/80319137-0cde3e80-880f-11ea-8254-de30a9ddb02f.png)

The code

![1](https://user-images.githubusercontent.com/13602797/80319190-765e4d00-880f-11ea-8f4b-2fc158f4c20d.png)
![2](https://user-images.githubusercontent.com/13602797/80319194-79f1d400-880f-11ea-9ef0-44536b8b8671.png)
![3](https://user-images.githubusercontent.com/13602797/80319196-7c542e00-880f-11ea-8bf7-05a26d086a36.png)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | 0.1.0-beta.5
| React            |16.13.1
| TypeScript       |3.7.2
| Browser          | Chrome
| npm/Yarn         |6.13.4
| Operating System | MacOS Catalina 10.15.2

**Comment by madhavgharmalkar** [comment]
Any help on this? Running into the same issue

**Comment by prevwong** [comment]
@riccardocaranfil @madhavgharmalkar Sorry for the late reply, but I've tried the code posted above a couple of days ago, but I didn't manage to replicate the issue. If you could share your code on a public repo for me to try out, that would be super helpful!

**Comment by madhavgharmalkar** [comment]
@prevwong thanks for getting back to us!

I'm running a very basic example here
```
 <Craft>
        <Box>
          <Frame>
            <Canvas padding={5}>
              <button>test</button>
            </Canvas>
          </Frame>
        </Box>
      </Craft>
```

and this is my outputted DOM

<img width="400" alt="image" src="https://user-images.githubusercontent.com/8007933/81097995-9354e900-8ebd-11ea-8e15-f08656795ef3.png">

**Comment by prevwong** [comment]
@madhavgharmalkar @riccardocaranfil Please try again with the latest release on NPM, hopefully it solves the problem for you. Seems to be an issue with our `.add` action. We're doing some refactoring, but meanwhile this hotfix should work for now 😄

**Comment by madhavgharmalkar** [comment]
@prevwong Thank you!

**Comment by riccardocaranfil** [comment]
@prevwong Sorry for the late response, Thanks!
