### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by andreiwow2** [prevwong/craft.js#686]
**Describe the bug**
I  get `Could not find a declaration file for module` for this package, I'm not sure what I am doing wrong or why the types aren't being installed..

**To Reproduce**

Install the package in a project that uses pnpm or npm, tried with both.

**Expected behavior**
Should correctly find the package types

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         |    ^0.2.9
| React            |    ^18
| TypeScript       |  ^5
| Browser          |
| npm/Yarn         | npm@10.7.0
| Operating System | windows 11

**Comment by qingzhoufeihu** [comment]
Don't worry bro, try to restart your vscode 😁

**Comment by andreiwow2** [comment]
> Don't worry bro, try to restart your vscode or restart your ts engine in your vscode 😁

I don't think that is the root of my issue, I tried to reload my VSCode and the error is still there, also, looking at the craftjs folder in my node_modules, I can't find any types or lib folder

![image](https://github.com/user-attachments/assets/e411bfd3-3a5b-45f0-9953-7aa49349fe0c)

And based on the `package.json` of craft, it should be at `/lib/index.d.ts

**Comment by prevwong** [comment]
My bad! Updated package.json and accidentally omitted the typings folder. Fixed in 0.2.10 (#687)
