### ISSUE TITLE
Indicator width over the line

### ISSUE THREAD

**Issue by sprabowo** [prevwong/craft.js#71]
**Describe the bug**
when i try to add Layers on left. i see that indicator over the line (offside)

**To Reproduce**
please review this https://github.com/prevwong/craft.js/pull/70

**Expected behavior**
it should be the same width

**Screenshots**
<img width="358" alt="Screen Shot 2020-05-06 at 14 34 26" src="https://user-images.githubusercontent.com/11748183/81149831-27e84580-8fa9-11ea-89e2-0bda426254a0.png">

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | 0.1.0-beta.5

**Comment by noahbaron91** [comment]
Hey! How did you end up fixing this? I'm having the same issue

**Comment by sprabowo** [comment]
Hi @noahbaron91 could you check this PR https://github.com/prevwong/craft.js/pull/70
