### ISSUE TITLE
Attempting to add a node with duplicated id

### ISSUE THREAD

**Issue by dadwic** [prevwong/craft.js#78]
Unhandled Runtime Error
Error: Error: Invariant failed: Attempting to add a node with duplicated id

### Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | 0.1.0-beta.6
| React            | 16.8.6
| Browser          | Chrome 83
| npm/Yarn         | 6.14.4
| Operating System | MacOS 10.15.4

![Screen Shot 2020-06-09 at 2 44 52 PM](https://user-images.githubusercontent.com/13819774/84135945-d592bc80-aa5f-11ea-9a6e-ad76cab2ffd7.png)

**Comment by prevwong** [comment]
Hey @dadwic, do you have a brief code example that you could share?
