### ISSUE TITLE
How to override the default drag event handler? 

### ISSUE THREAD

**Issue by mazz-seven** [prevwong/craft.js#79]
I'm trying to understand if there is an easy way to implement a different drag event handler. 
I want it to be free dragging. 
I saw issue #32 , but this implementation doesn't provide a way to drop the element on a different canvas.

P.S 
Thank you for the hard work you put into this library!

**Comment by prevwong** [comment]
Hey @mazz-seven! 👋 

Unfortunately, this is not possible right now.

For the time being, a potential alternative is you could just not use the included `connectors`, and add your own DOM event handlers and that might work. Eg: you could just add your own drag/drop event handlers to your components to handle the events and logic.

**Comment by prevwong** [comment]
@mazz-seven Just to clarify on my comment - it's not possible to override the included connectors (eg: you can't make `connectors.drag` from `useEditor`/`useNode` to do something else).

But you don't have to use the included connectors and you can very much write your own to perform the actions that you want. A nice way of doing this would be to extend the `Handlers` class, which would even allow you to reuse the included connectors.

Here's an example from our layers package on how to do this:

1. Extend the `Handlers` class: https://github.com/prevwong/craft.js/blob/b3c95ee8d829fa9797e4f508561e69cc3758f37e/packages/layers/src/events/LayerHandlers.ts

2. Then, you can get the connectors and use them as usual: https://github.com/prevwong/craft.js/blob/b3c95ee8d829fa9797e4f508561e69cc3758f37e/packages/layers/src/layers/LayerContextProvider.tsx#L15-L18

I should probably write a proper guide on this 😄 But yeah, hopefully this helps for now!

**Comment by mazz-seven** [comment]
This is exactly what I was looking for. Thank you!
