### ISSUE TITLE
file uploading  with page builder

### ISSUE THREAD

**Issue by codeporan** [prevwong/craft.js#8]
I am looking for file uploading for react application.

**Comment by FFCoder** [comment]
A File Uploading Module for CraftJS or how to upload files with React?

**Comment by codeporan** [comment]
I need A File Uploading Module for CraftJS

**Comment by prevwong** [comment]
@codeporan Could you recreate this issue with the **Feature Request** issue template provided ? It would help provide us with a bit more context.

**Comment by codeporan** [comment]
thanks

**Comment by ackvf** [comment]
@codeporan You can take any existing file uploading solution and use it in your custom component as you would use in any React app. Craft.js is just a wysiwyg block builder. You can build your blocks however you want. Or am I missing something?

**Comment by codeporan** [comment]
you exactly right
