### ISSUE TITLE
State is not initiated

### ISSUE THREAD

**Issue by thedv91** [prevwong/craft.js#95]
Hi everyone

I follow guide for a basic tutorial on the link: [https://craft.js.org/r/docs/guides/basic-tutorial](https://craft.js.org/r/docs/guides/basic-tutorial).

But when I saved state to localStorage and reload the page, the content is not filled automatically in Card.

Anybody can help? 

Thanks!

**Comment by prevwong** [comment]
Hi @thedv91 👋 

Could you share your code on how you're saving the state to and from local storage?

**Comment by thedv91** [comment]
@prevwong This is my code 

```js
const base64 = `eyJST09UIjp7InR5cGXECHJlc29sdmVkTmFtZSI6IkNvbnRhaW5lciJ9LCJpc0NhbnZhcyI6dHJ1ZSwicHJvcHPENWJhY2tncm91bmQiOiIjZcUBIiwicGFkZGluZyI6NX0sImRpc3BsYXnHWGTEIGN1c3RvbSI6e30sImhpZGRlbiI6ZmFsc2UsIm5vZGVzIjpbIlRyTTFDd0ZxOFQiLCI3WVZBVFFWXzBjIiwiV1IzVDBpbElpeSIsInhTVGkzbnRlMzIiXX0szDb7ANxhcmTkANf3AMdmxQHsAMcz8QDHxUP9AMlwYXJlbnQiOuYBaSwibGlua2VkTuYA33sidGV4xB03MWsxTzktWXBiIiwiYnV0dG9uc+QBJjNEcTJQR3JSdSJ9fe0A//oA1kLFPu0A2HNpesQac21hbGwiLCJ2YXJpYeUAlGPnAd7lAMRvbG9yIjoicHJpbWFy5AFU5wCcQ2xpY2sgbWXEU+4A/sdr/wEA7AEAfe0Bt/oAxVTEe+wAw+cAjEhpIHdvcmxkISIsImZvbnRT5QDaMjDxAJvFQf8Ame8AmesCQ/8DEP8DEPACSTnFAewCSTb/AxD7AxBneEZ1ZWRzeldnIl3zAMXLH/8BXvMBXkl0J3MgbWUgYWdhaW7wAWMs7gJH/wFy/QFy6wFq5ALW6gL8/gOsVG9w/AF2/wFU+wFUSS1Xalg0NExYVSIsIlRESlVpV0hQczntAWHrBFJ9LMwy/wFn8wFnT25seSDEDHP/Asb/AVTtAVTrAUbkBQDqAMX/AKDzAKBEZW1vIGNoYW5n5QQZ6gCiMfIFyP8AovoAousE2/4B9kJvdMRb/wH5/wH59wH5UENwVHJ6V3plTfsB7Msl/wV2/wV2/wV27gV25QIl5wYKIGRvd24gaGVy/wWE/wGD7wZQ`;
  const json = lz.decompress(lz.decodeBase64(base64));

/// other code
   <Frame data={json}>
       ...
       ...
   </Frame>

```

I cloned code from https://github.com/prevwong/craft.js/tree/develop/packages/examples/basic

**Comment by prevwong** [comment]
That doesn't load anything from local storage. It simply decompresses the base64 state and loads that into the editor. You need to first save the state to local storage, then retrieve and load the state here

**Comment by thedv91** [comment]
Sorry, I missed the save to localStorage step. But my issue is the Card component not update when initialization data has changed.
