### ISSUE TITLE
Component dom property got undefined after deserialize async json

### ISSUE THREAD

**Issue by dadwic** [prevwong/craft.js#99]
Hi there, when I deserialize the json that fetched from the server components are displayed but some of them do not have dom property for render indicator.

### environment 

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js         | 0.1.0-beta.8
| React            | 16.8.6

@prevwong @ankri

**Comment by prevwong** [comment]
@hdaggett Fixed in beta.9! 🎆
